import type { Game } from "./types";

function steamCover(appId: number) {
  return `https://cdn.akamai.steamstatic.com/steam/apps/${appId}/library_600x900.jpg`;
}
function steamBackdrop(appId: number) {
  return `https://cdn.akamai.steamstatic.com/steam/apps/${appId}/library_hero.jpg`;
}
function steamUrl(appId: number) {
  return `https://store.steampowered.com/app/${appId}`;
}
function epicUrl(slug: string) {
  return `https://store.epicgames.com/en-US/p/${slug}`;
}
function gogUrl(slug: string) {
  return `https://www.gog.com/en/game/${slug}`;
}

export const games: Game[] = [
  {
    id: "hl2",
    slug: "half-life-2",
    title: "Half-Life 2",
    year: 2004,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Sci-Fi", "Action"],
    tags: ["Classic", "Story Rich", "Physics"],
    description:
      "Gordon Freeman returns to fight the alien occupation of Earth in a shooter still studied for its pacing, physics puzzles and set-pieces two decades on.",
    cover: steamCover(220),
    backdrop: steamBackdrop(220),
    stores: { steam: { url: steamUrl(220) } },
    communityRating: 4.7,
    ratingCount: 128430,
  },
  {
    id: "portal2",
    slug: "portal-2",
    title: "Portal 2",
    year: 2011,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Puzzle", "Sci-Fi", "Adventure"],
    tags: ["Co-op", "Comedy", "Story Rich"],
    description:
      "A portal gun, a passive-aggressive AI, and some of the best-written puzzle design ever shipped. The co-op campaign is essential.",
    cover: steamCover(620),
    backdrop: steamBackdrop(620),
    stores: { steam: { url: steamUrl(620) } },
    communityRating: 4.9,
    ratingCount: 141220,
  },
  {
    id: "cyberpunk2077",
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    year: 2020,
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Sci-Fi"],
    tags: ["Night City", "First-Person", "Story Rich"],
    description:
      "After a rocky launch, Night City has become one of the densest open worlds around — a cyberpunk crime story with real weight behind its choices.",
    cover: steamCover(1091500),
    backdrop: steamBackdrop(1091500),
    stores: {
      steam: { url: steamUrl(1091500) },
      gog: { url: gogUrl("cyberpunk_2077") },
      epic: { url: epicUrl("cyberpunk-2077-a71bc4") },
    },
    communityRating: 4.4,
    ratingCount: 98220,
  },
  {
    id: "witcher3",
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    year: 2015,
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Fantasy"],
    tags: ["Story Rich", "Monster Hunting", "Classic"],
    description:
      "Geralt's last contract is still the benchmark for open-world RPG writing — every side quest reads like it mattered.",
    cover: steamCover(292030),
    backdrop: steamBackdrop(292030),
    stores: {
      steam: { url: steamUrl(292030) },
      gog: { url: gogUrl("the_witcher_3_wild_hunt") },
      epic: { url: epicUrl("the-witcher-3-wild-hunt") },
    },
    communityRating: 4.9,
    ratingCount: 205110,
  },
  {
    id: "bg3",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genres: ["RPG", "Fantasy", "Strategy"],
    tags: ["Turn-Based", "Co-op", "D&D"],
    description:
      "A turn-based D&D epic with an absurd amount of reactivity — almost anything you try has a hand-built response waiting for it.",
    cover: steamCover(1086940),
    backdrop: steamBackdrop(1086940),
    stores: {
      steam: { url: steamUrl(1086940) },
      gog: { url: gogUrl("baldurs_gate_3") },
    },
    communityRating: 4.9,
    ratingCount: 176500,
  },
  {
    id: "eldenring",
    slug: "elden-ring",
    title: "Elden Ring",
    year: 2022,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Souls-like", "Open World", "Fantasy"],
    tags: ["Difficult", "Atmospheric", "Boss Rush"],
    description:
      "FromSoftware's open world take on the souls formula, co-written with George R. R. Martin's lore — bleak, huge, and unforgiving.",
    cover: steamCover(1245620),
    backdrop: steamBackdrop(1245620),
    stores: { steam: { url: steamUrl(1245620) } },
    communityRating: 4.7,
    ratingCount: 143870,
  },
  {
    id: "hades",
    slug: "hades",
    title: "Hades",
    year: 2020,
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genres: ["Roguelike", "Action", "Indie"],
    tags: ["Greek Mythology", "Story Rich", "Isometric"],
    description:
      "Every failed escape attempt from the Underworld peels back more story. Rare for a roguelike to have this much heart.",
    cover: steamCover(1145360),
    backdrop: steamBackdrop(1145360),
    stores: {
      steam: { url: steamUrl(1145360) },
      gog: { url: gogUrl("hades") },
      epic: { url: epicUrl("hades-c0feb1") },
    },
    communityRating: 4.9,
    ratingCount: 132040,
  },
  {
    id: "stardewvalley",
    slug: "stardew-valley",
    title: "Stardew Valley",
    year: 2016,
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    genres: ["Simulation", "RPG", "Indie"],
    tags: ["Farming", "Cozy", "Multiplayer"],
    description:
      "One developer built a farming sim deep enough to eat entire winters. Still gets free content updates years later.",
    cover: steamCover(413150),
    backdrop: steamBackdrop(413150),
    stores: {
      steam: { url: steamUrl(413150) },
      gog: { url: gogUrl("stardew_valley") },
      epic: { url: epicUrl("stardew-valley") },
    },
    communityRating: 4.8,
    ratingCount: 189330,
  },
  {
    id: "hollowknight",
    slug: "hollow-knight",
    title: "Hollow Knight",
    year: 2017,
    developer: "Team Cherry",
    publisher: "Team Cherry",
    genres: ["Metroidvania", "Indie", "Action"],
    tags: ["Atmospheric", "Difficult", "Hand-Drawn"],
    description:
      "A hand-drawn metroidvania with one of the best-designed maps in the genre and a soundtrack that still lives rent-free.",
    cover: steamCover(367520),
    backdrop: steamBackdrop(367520),
    stores: {
      steam: { url: steamUrl(367520) },
      gog: { url: gogUrl("hollow_knight") },
      epic: { url: epicUrl("hollow-knight") },
    },
    communityRating: 4.8,
    ratingCount: 121980,
  },
  {
    id: "discoelysium",
    slug: "disco-elysium",
    title: "Disco Elysium: The Final Cut",
    year: 2021,
    developer: "ZA/UM",
    publisher: "ZA/UM",
    genres: ["RPG", "Narrative", "Indie"],
    tags: ["Detective", "Dialogue Heavy", "Dark Comedy"],
    description:
      "No combat, all conversation — a detective RPG where your own skills argue with you in your head. Best-in-class writing.",
    cover: steamCover(632470),
    backdrop: steamBackdrop(632470),
    stores: {
      steam: { url: steamUrl(632470) },
      gog: { url: gogUrl("disco_elysium_the_final_cut") },
      epic: { url: epicUrl("disco-elysium-the-final-cut") },
    },
    communityRating: 4.8,
    ratingCount: 60110,
  },
  {
    id: "terraria",
    slug: "terraria",
    title: "Terraria",
    year: 2011,
    developer: "Re-Logic",
    publisher: "Re-Logic",
    genres: ["Sandbox", "Action", "Indie"],
    tags: ["Crafting", "2D", "Multiplayer"],
    description:
      "2D sandbox crafting/adventure that has been quietly getting free major updates for over a decade.",
    cover: steamCover(105600),
    backdrop: steamBackdrop(105600),
    stores: {
      steam: { url: steamUrl(105600) },
      gog: { url: gogUrl("terraria") },
    },
    communityRating: 4.8,
    ratingCount: 175430,
  },
  {
    id: "celeste",
    slug: "celeste",
    title: "Celeste",
    year: 2018,
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    genres: ["Platformer", "Indie"],
    tags: ["Difficult", "Story Rich", "Pixel Art"],
    description:
      "A precision platformer about climbing a mountain and your own anxiety, with some of the tightest movement controls in the genre.",
    cover: steamCover(504230),
    backdrop: steamBackdrop(504230),
    stores: {
      steam: { url: steamUrl(504230) },
      gog: { url: gogUrl("celeste") },
      epic: { url: epicUrl("celeste") },
    },
    communityRating: 4.8,
    ratingCount: 48210,
  },
  {
    id: "deadcells",
    slug: "dead-cells",
    title: "Dead Cells",
    year: 2018,
    developer: "Motion Twin",
    publisher: "Motion Twin",
    genres: ["Roguelike", "Metroidvania", "Action"],
    tags: ["Difficult", "2D", "Fast-Paced"],
    description:
      "A roguevania that controls like a character-action game. Years of free updates have made it one of the deepest builds-based games around.",
    cover: steamCover(588650),
    backdrop: steamBackdrop(588650),
    stores: {
      steam: { url: steamUrl(588650) },
      gog: { url: gogUrl("dead_cells") },
      epic: { url: epicUrl("dead-cells") },
    },
    communityRating: 4.8,
    ratingCount: 71340,
  },
  {
    id: "rdr2",
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    year: 2019,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["Open World", "Action", "Western"],
    tags: ["Story Rich", "Atmospheric", "Realistic"],
    description:
      "An outlaw epic that treats its dying frontier as seriously as its characters — glacial pace, enormous payoff.",
    cover: steamCover(1174180),
    backdrop: steamBackdrop(1174180),
    stores: {
      steam: { url: steamUrl(1174180) },
      epic: { url: epicUrl("red-dead-redemption-2") },
    },
    communityRating: 4.7,
    ratingCount: 156700,
  },
  {
    id: "gtav",
    slug: "grand-theft-auto-v",
    title: "Grand Theft Auto V",
    year: 2013,
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    genres: ["Open World", "Action", "Crime"],
    tags: ["Multiplayer", "Satire", "Classic"],
    description:
      "Three protagonists, one sprawling satire of Southern California, and a GTA Online mode that's outlived every prediction.",
    cover: steamCover(271590),
    backdrop: steamBackdrop(271590),
    stores: {
      steam: { url: steamUrl(271590) },
      epic: { url: epicUrl("grand-theft-auto-v") },
    },
    communityRating: 4.3,
    ratingCount: 198400,
  },
  {
    id: "doometernal",
    slug: "doom-eternal",
    title: "DOOM Eternal",
    year: 2020,
    developer: "id Software",
    publisher: "Bethesda Softworks",
    genres: ["Shooter", "Action"],
    tags: ["Fast-Paced", "Gore", "Metal Soundtrack"],
    description:
      "id Software turns the shooter into a rhythm game of resource management at maximum speed. Exhausting in the best way.",
    cover: steamCover(782330),
    backdrop: steamBackdrop(782330),
    stores: {
      steam: { url: steamUrl(782330) },
      epic: { url: epicUrl("doom-eternal") },
    },
    communityRating: 4.6,
    ratingCount: 65230,
  },
  {
    id: "sekiro",
    slug: "sekiro-shadows-die-twice",
    title: "Sekiro: Shadows Die Twice",
    year: 2019,
    developer: "FromSoftware",
    publisher: "Activision",
    genres: ["Souls-like", "Action", "Fantasy"],
    tags: ["Difficult", "Samurai", "Parry-Focused"],
    description:
      "Posture-breaking swordplay makes this the sharpest combat FromSoftware has ever built, at the cost of any easy mode.",
    cover: steamCover(814380),
    backdrop: steamBackdrop(814380),
    stores: { steam: { url: steamUrl(814380) } },
    communityRating: 4.7,
    ratingCount: 84120,
  },
  {
    id: "darksouls3",
    slug: "dark-souls-3",
    title: "Dark Souls III",
    year: 2016,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Souls-like", "Action", "Fantasy"],
    tags: ["Difficult", "Atmospheric", "Boss Rush"],
    description:
      "The trilogy's send-off, tighter and faster than its predecessors, closing out Lordran's story with some of the series' best bosses.",
    cover: steamCover(374320),
    backdrop: steamBackdrop(374320),
    stores: { steam: { url: steamUrl(374320) } },
    communityRating: 4.7,
    ratingCount: 97650,
  },
  {
    id: "dos2",
    slug: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    year: 2017,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genres: ["RPG", "Strategy", "Fantasy"],
    tags: ["Turn-Based", "Co-op", "Story Rich"],
    description:
      "Larian's warm-up for Baldur's Gate 3 — elemental combos and environmental chaos in a turn-based RPG that rewards creativity.",
    cover: steamCover(435150),
    backdrop: steamBackdrop(435150),
    stores: {
      steam: { url: steamUrl(435150) },
      gog: { url: gogUrl("divinity_original_sin_2") },
      epic: { url: epicUrl("divinity-original-sin-2") },
    },
    communityRating: 4.8,
    ratingCount: 55870,
  },
  {
    id: "slaythespire",
    slug: "slay-the-spire",
    title: "Slay the Spire",
    year: 2019,
    developer: "Mega Crit",
    publisher: "Mega Crit",
    genres: ["Deck-builder", "Roguelike", "Strategy"],
    tags: ["Card Game", "Difficult", "Replayable"],
    description:
      "The game that turned deck-building into a roguelike genre of its own. Endlessly replayable, brutally balanced.",
    cover: steamCover(646570),
    backdrop: steamBackdrop(646570),
    stores: {
      steam: { url: steamUrl(646570) },
      gog: { url: gogUrl("slay_the_spire") },
      epic: { url: epicUrl("slay-the-spire") },
    },
    communityRating: 4.7,
    ratingCount: 61200,
  },
  {
    id: "undertale",
    slug: "undertale",
    title: "Undertale",
    year: 2015,
    developer: "tobyfox",
    publisher: "tobyfox",
    genres: ["RPG", "Indie", "Narrative"],
    tags: ["Story Rich", "Pixel Art", "Comedy"],
    description:
      "A bullet-hell RPG that remembers everything you do and asks whether you needed to fight at all. Still catches people off guard.",
    cover: steamCover(391540),
    backdrop: steamBackdrop(391540),
    stores: {
      steam: { url: steamUrl(391540) },
      gog: { url: gogUrl("undertale") },
    },
    communityRating: 4.8,
    ratingCount: 88450,
  },
  {
    id: "oriwotw",
    slug: "ori-and-the-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    year: 2020,
    developer: "Moon Studios",
    publisher: "Xbox Game Studios",
    genres: ["Metroidvania", "Platformer", "Adventure"],
    tags: ["Beautiful", "Atmospheric", "Story Rich"],
    description:
      "Some of the most gorgeous hand-painted backdrops in the genre, wrapped around movement that feels incredible by the final act.",
    cover: steamCover(1057090),
    backdrop: steamBackdrop(1057090),
    stores: {
      steam: { url: steamUrl(1057090) },
      epic: { url: epicUrl("ori-and-the-will-of-the-wisps") },
    },
    communityRating: 4.8,
    ratingCount: 26340,
  },
  {
    id: "ittakestwo",
    slug: "it-takes-two",
    title: "It Takes Two",
    year: 2021,
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    genres: ["Platformer", "Adventure", "Co-op"],
    tags: ["Co-op Only", "Inventive", "Story Rich"],
    description:
      "A two-player-only adventure that reinvents its core mechanics almost every chapter. Rare to see this much ambition in co-op design.",
    cover: steamCover(1426210),
    backdrop: steamBackdrop(1426210),
    stores: {
      steam: { url: steamUrl(1426210) },
      epic: { url: epicUrl("it-takes-two") },
    },
    communityRating: 4.8,
    ratingCount: 42110,
  },
  {
    id: "balatro",
    slug: "balatro",
    title: "Balatro",
    year: 2024,
    developer: "LocalThunk",
    publisher: "Playstack",
    genres: ["Deck-builder", "Roguelike", "Card Game"],
    tags: ["Poker", "Addictive", "Indie"],
    description:
      "Poker-hand scoring turned into a roguelike deck-builder that eats entire evenings without you noticing. Deceptively deep.",
    cover: steamCover(2379780),
    backdrop: steamBackdrop(2379780),
    stores: {
      steam: { url: steamUrl(2379780) },
      gog: { url: gogUrl("balatro") },
      epic: { url: epicUrl("balatro") },
    },
    communityRating: 4.8,
    ratingCount: 39870,
  },
  {
    id: "vampiresurvivors",
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    year: 2022,
    developer: "poncle",
    publisher: "poncle",
    genres: ["Roguelike", "Action", "Indie"],
    tags: ["Bullet Heaven", "Pixel Art", "Cheap"],
    description:
      "The game that named an entire new genre. Absurdly cheap, absurdly replayable auto-battling chaos.",
    cover: steamCover(1794680),
    backdrop: steamBackdrop(1794680),
    stores: {
      steam: { url: steamUrl(1794680) },
      gog: { url: gogUrl("vampire_survivors") },
      epic: { url: epicUrl("vampire-survivors") },
    },
    communityRating: 4.7,
    ratingCount: 40120,
  },
  {
    id: "outerwilds",
    slug: "outer-wilds",
    title: "Outer Wilds",
    year: 2019,
    developer: "Mobius Digital",
    publisher: "Annapurna Interactive",
    genres: ["Adventure", "Puzzle", "Sci-Fi"],
    tags: ["Mystery", "Exploration", "Time Loop"],
    description:
      "A 22-minute time loop and a solar system full of secrets. Knowledge is the only upgrade, which makes every discovery permanent.",
    cover: steamCover(753640),
    backdrop: steamBackdrop(753640),
    stores: {
      steam: { url: steamUrl(753640) },
      epic: { url: epicUrl("outer-wilds") },
    },
    communityRating: 4.9,
    ratingCount: 33980,
  },
  {
    id: "cultofthelamb",
    slug: "cult-of-the-lamb",
    title: "Cult of the Lamb",
    year: 2022,
    developer: "Massive Monster",
    publisher: "Devolver Digital",
    genres: ["Roguelike", "Simulation", "Indie"],
    tags: ["Cute", "Dark Comedy", "Base Building"],
    description:
      "Run a cult by day, roguelike your way through corrupted lands by night. Devolver's chaotic sense of humor all over it.",
    cover: steamCover(1313140),
    backdrop: steamBackdrop(1313140),
    stores: {
      steam: { url: steamUrl(1313140) },
      gog: { url: gogUrl("cult_of_the_lamb") },
      epic: { url: epicUrl("cult-of-the-lamb") },
    },
    communityRating: 4.5,
    ratingCount: 28770,
  },
  {
    id: "control",
    slug: "control",
    title: "Control",
    year: 2019,
    developer: "Remedy Entertainment",
    publisher: "505 Games",
    genres: ["Action", "Sci-Fi", "Adventure"],
    tags: ["Atmospheric", "Telekinesis", "Story Rich"],
    description:
      "Remedy's brutalist bureaucratic horror, with telekinetic combat that turns entire offices into ammunition.",
    cover: steamCover(870780),
    backdrop: steamBackdrop(870780),
    stores: {
      steam: { url: steamUrl(870780) },
      epic: { url: epicUrl("control") },
    },
    communityRating: 4.5,
    ratingCount: 31200,
  },
  {
    id: "portal",
    slug: "portal",
    title: "Portal",
    year: 2007,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Puzzle", "Sci-Fi", "Adventure"],
    tags: ["Classic", "Short", "Comedy"],
    description:
      "The one that started it all — a four-hour puzzle box that rewired how people think about first-person game design.",
    cover: steamCover(400),
    backdrop: steamBackdrop(400),
    stores: { steam: { url: steamUrl(400) } },
    communityRating: 4.9,
    ratingCount: 98650,
  },
  {
    id: "tf2",
    slug: "team-fortress-2",
    title: "Team Fortress 2",
    year: 2007,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Action"],
    tags: ["Free to Play", "Class-Based", "Multiplayer"],
    description:
      "Nine overdesigned classes, near-perfect map design, and a hat economy that somehow still runs. Still one of the best shooters made.",
    cover: steamCover(440),
    backdrop: steamBackdrop(440),
    stores: { steam: { url: steamUrl(440) } },
    communityRating: 4.6,
    ratingCount: 87340,
  },
  {
    id: "cs2",
    slug: "counter-strike-2",
    title: "Counter-Strike 2",
    year: 2023,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Action", "Esports"],
    tags: ["Free to Play", "Competitive", "Tactical"],
    description:
      "The reigning tactical shooter, rebuilt on Source 2. Still the benchmark for gunplay precision two decades into the franchise.",
    cover: steamCover(730),
    backdrop: steamBackdrop(730),
    stores: { steam: { url: steamUrl(730) } },
    communityRating: 4.3,
    ratingCount: 154200,
  },
  {
    id: "rocketleague",
    slug: "rocket-league",
    title: "Rocket League",
    year: 2015,
    developer: "Psyonix",
    publisher: "Psyonix",
    genres: ["Sports", "Action", "Multiplayer"],
    tags: ["Free to Play", "Competitive", "Cars"],
    description:
      "Soccer, but with rocket-powered cars. Simple pitch, absurdly deep skill ceiling once you learn to fly.",
    cover: steamCover(252950),
    backdrop: steamBackdrop(252950),
    stores: {
      steam: { url: steamUrl(252950) },
      epic: { url: epicUrl("rocket-league") },
    },
    communityRating: 4.5,
    ratingCount: 112400,
  },
  {
    id: "amongus",
    slug: "among-us",
    title: "Among Us",
    year: 2018,
    developer: "InnerSloth",
    publisher: "InnerSloth",
    genres: ["Social Deduction", "Multiplayer", "Indie"],
    tags: ["Party Game", "Cross-Platform", "Cheap"],
    description:
      "A lobby of nine crewmates and a saboteur or two. The 2020 sleeper hit that made everyone suspicious of their friends.",
    cover: steamCover(945360),
    backdrop: steamBackdrop(945360),
    stores: {
      steam: { url: steamUrl(945360) },
      gog: { url: gogUrl("among_us") },
      epic: { url: epicUrl("among-us") },
    },
    communityRating: 4.2,
    ratingCount: 76300,
  },
  {
    id: "cuphead",
    slug: "cuphead",
    title: "Cuphead",
    year: 2017,
    developer: "StudioMDHR",
    publisher: "StudioMDHR",
    genres: ["Platformer", "Action", "Indie"],
    tags: ["Difficult", "Hand-Drawn", "Boss Rush"],
    description:
      "Hand-inked 1930s cartoon aesthetics wrapped around a run-and-gun that shows zero mercy. The art alone took years.",
    cover: steamCover(268910),
    backdrop: steamBackdrop(268910),
    stores: {
      steam: { url: steamUrl(268910) },
      gog: { url: gogUrl("cuphead") },
      epic: { url: epicUrl("cuphead") },
    },
    communityRating: 4.7,
    ratingCount: 68900,
  },
  {
    id: "firewatch",
    slug: "firewatch",
    title: "Firewatch",
    year: 2016,
    developer: "Campo Santo",
    publisher: "Panic",
    genres: ["Narrative", "Adventure", "Indie"],
    tags: ["Story Rich", "First-Person", "Atmospheric"],
    description:
      "Two people talk on a radio in a Wyoming forest and it somehow becomes one of the best-written games of the decade.",
    cover: steamCover(383870),
    backdrop: steamBackdrop(383870),
    stores: {
      steam: { url: steamUrl(383870) },
      gog: { url: gogUrl("firewatch") },
      epic: { url: epicUrl("firewatch") },
    },
    communityRating: 4.4,
    ratingCount: 41200,
  },
  {
    id: "hyperlightdrifter",
    slug: "hyper-light-drifter",
    title: "Hyper Light Drifter",
    year: 2016,
    developer: "Heart Machine",
    publisher: "Heart Machine",
    genres: ["Action", "Adventure", "Indie"],
    tags: ["Pixel Art", "Atmospheric", "Difficult"],
    description:
      "A wordless, dying world told entirely through pixel art and a combat system with real weight behind every swing.",
    cover: steamCover(257850),
    backdrop: steamBackdrop(257850),
    stores: {
      steam: { url: steamUrl(257850) },
      gog: { url: gogUrl("hyper_light_drifter") },
      epic: { url: epicUrl("hyper-light-drifter") },
    },
    communityRating: 4.5,
    ratingCount: 29800,
  },
  {
    id: "katanazero",
    slug: "katana-zero",
    title: "Katana ZERO",
    year: 2019,
    developer: "Askiisoft",
    publisher: "Devolver Digital",
    genres: ["Platformer", "Action", "Indie"],
    tags: ["Neo-Noir", "One-Hit Kill", "Story Rich"],
    description:
      "One-hit-kill action with a rewind mechanic and a neo-noir story that keeps getting stranger. Over too soon in the best way.",
    cover: steamCover(460950),
    backdrop: steamBackdrop(460950),
    stores: {
      steam: { url: steamUrl(460950) },
      gog: { url: gogUrl("katana_zero") },
      epic: { url: epicUrl("katana-zero") },
    },
    communityRating: 4.7,
    ratingCount: 33500,
  },
  {
    id: "inscryption",
    slug: "inscryption",
    title: "Inscryption",
    year: 2021,
    developer: "Daniel Mullins Games",
    publisher: "Devolver Digital",
    genres: ["Deck-builder", "Horror", "Puzzle"],
    tags: ["Card Game", "Story Rich", "Meta"],
    description:
      "A card-battling roguelike that keeps breaking its own frame. Say as little about it going in as possible.",
    cover: steamCover(1092790),
    backdrop: steamBackdrop(1092790),
    stores: {
      steam: { url: steamUrl(1092790) },
      gog: { url: gogUrl("inscryption") },
      epic: { url: epicUrl("inscryption") },
    },
    communityRating: 4.8,
    ratingCount: 37600,
  },
  {
    id: "inside",
    slug: "inside",
    title: "Inside",
    year: 2016,
    developer: "Playdead",
    publisher: "Playdead",
    genres: ["Puzzle", "Platformer", "Horror"],
    tags: ["Atmospheric", "Story Rich", "Short"],
    description:
      "A silent, unsettling puzzle-platformer from the Limbo team, with an ending people are still arguing about.",
    cover: steamCover(304430),
    backdrop: steamBackdrop(304430),
    stores: {
      steam: { url: steamUrl(304430) },
      gog: { url: gogUrl("inside") },
      epic: { url: epicUrl("inside") },
    },
    communityRating: 4.7,
    ratingCount: 44100,
  },
  {
    id: "limbo",
    slug: "limbo",
    title: "Limbo",
    year: 2011,
    developer: "Playdead",
    publisher: "Playdead",
    genres: ["Puzzle", "Platformer", "Horror"],
    tags: ["Atmospheric", "Black and White", "Short"],
    description:
      "The monochrome puzzle-platformer that proved indie games could be genuinely unsettling. Still holds up.",
    cover: steamCover(48000),
    backdrop: steamBackdrop(48000),
    stores: {
      steam: { url: steamUrl(48000) },
      gog: { url: gogUrl("limbo") },
      epic: { url: epicUrl("limbo") },
    },
    communityRating: 4.6,
    ratingCount: 52300,
  },
  {
    id: "stanleyparable",
    slug: "the-stanley-parable-ultra-deluxe",
    title: "The Stanley Parable: Ultra Deluxe",
    year: 2022,
    developer: "Crows Crows Crows",
    publisher: "Crows Crows Crows",
    genres: ["Narrative", "Puzzle", "Comedy"],
    tags: ["Meta", "First-Person", "Satire"],
    description:
      "A choice-driven walking sim that spends its entire runtime mocking the idea of choice-driven walking sims. Extremely funny.",
    cover: steamCover(1703340),
    backdrop: steamBackdrop(1703340),
    stores: {
      steam: { url: steamUrl(1703340) },
      gog: { url: gogUrl("the_stanley_parable_ultra_deluxe") },
      epic: { url: epicUrl("the-stanley-parable-ultra-deluxe") },
    },
    communityRating: 4.6,
    ratingCount: 22100,
  },
  {
    id: "superliminal",
    slug: "superliminal",
    title: "Superliminal",
    year: 2019,
    developer: "Pillow Castle",
    publisher: "Pillow Castle",
    genres: ["Puzzle", "First-Person", "Indie"],
    tags: ["Perspective", "Short", "Trippy"],
    description:
      "A first-person puzzle game about forced perspective that keeps finding new ways to break your brain in a good way.",
    cover: steamCover(1049410),
    backdrop: steamBackdrop(1049410),
    stores: {
      steam: { url: steamUrl(1049410) },
      gog: { url: gogUrl("superliminal") },
      epic: { url: epicUrl("superliminal") },
    },
    communityRating: 4.4,
    ratingCount: 18700,
  },
  {
    id: "tunic",
    slug: "tunic",
    title: "Tunic",
    year: 2022,
    developer: "Isometricorp Games",
    publisher: "Finji",
    genres: ["Action", "Adventure", "Metroidvania"],
    tags: ["Zelda-Like", "Puzzle", "Instruction Manual"],
    description:
      "A tiny fox in a Zelda-like world, with an in-game instruction manual that turns into the real puzzle. Deeply clever.",
    cover: steamCover(553420),
    backdrop: steamBackdrop(553420),
    stores: {
      steam: { url: steamUrl(553420) },
      gog: { url: gogUrl("tunic") },
      epic: { url: epicUrl("tunic") },
    },
    communityRating: 4.6,
    ratingCount: 19400,
  },
  {
    id: "loophero",
    slug: "loop-hero",
    title: "Loop Hero",
    year: 2021,
    developer: "Four Quarters",
    publisher: "Devolver Digital",
    genres: ["Roguelike", "Strategy", "Indie"],
    tags: ["Deck-builder", "Pixel Art", "Automation"],
    description:
      "You place the tiles that build the world your hero walks in an endless loop. One of the most original roguelikes in years.",
    cover: steamCover(1282730),
    backdrop: steamBackdrop(1282730),
    stores: {
      steam: { url: steamUrl(1282730) },
      gog: { url: gogUrl("loop_hero") },
      epic: { url: epicUrl("loop-hero") },
    },
    communityRating: 4.5,
    ratingCount: 16200,
  },
  {
    id: "subnautica",
    slug: "subnautica",
    title: "Subnautica",
    year: 2018,
    developer: "Unknown Worlds Entertainment",
    publisher: "Unknown Worlds Entertainment",
    genres: ["Survival", "Adventure", "Open World"],
    tags: ["Underwater", "Crafting", "Atmospheric"],
    description:
      "An ocean survival game that turns thalassophobia into a core mechanic. Beautiful right up until something huge swims past.",
    cover: steamCover(264710),
    backdrop: steamBackdrop(264710),
    stores: {
      steam: { url: steamUrl(264710) },
      epic: { url: epicUrl("subnautica") },
    },
    communityRating: 4.7,
    ratingCount: 84600,
  },
  {
    id: "untitledgoosegame",
    slug: "untitled-goose-game",
    title: "Untitled Goose Game",
    year: 2019,
    developer: "House House",
    publisher: "Panic",
    genres: ["Puzzle", "Comedy", "Indie"],
    tags: ["Short", "Physics", "Silly"],
    description:
      "You are a horrible goose terrorizing an English village. A whole cultural moment for one very good comedic premise.",
    cover: steamCover(1046030),
    backdrop: steamBackdrop(1046030),
    stores: {
      steam: { url: steamUrl(1046030) },
      epic: { url: epicUrl("untitled-goose-game") },
    },
    communityRating: 4.3,
    ratingCount: 20900,
  },
  {
    id: "edithfinch",
    slug: "what-remains-of-edith-finch",
    title: "What Remains of Edith Finch",
    year: 2017,
    developer: "Giant Sparrow",
    publisher: "Annapurna Interactive",
    genres: ["Narrative", "Adventure", "Indie"],
    tags: ["Story Rich", "Short", "Emotional"],
    description:
      "A house full of dead relatives, each with a wildly different vignette telling their story. One of the best cases for games as fiction.",
    cover: steamCover(501300),
    backdrop: steamBackdrop(501300),
    stores: {
      steam: { url: steamUrl(501300) },
      epic: { url: epicUrl("what-remains-of-edith-finch") },
    },
    communityRating: 4.6,
    ratingCount: 27300,
  },
  {
    id: "riskofrain2",
    slug: "risk-of-rain-2",
    title: "Risk of Rain 2",
    year: 2020,
    developer: "Hopoo Games",
    publisher: "Gearbox Publishing",
    genres: ["Roguelike", "Shooter", "Action"],
    tags: ["Co-op", "3D", "Replayable"],
    description:
      "The 2D cult classic rebuilt in 3D without losing what made it work — stack absurd items until you become a walking apocalypse.",
    cover: steamCover(632360),
    backdrop: steamBackdrop(632360),
    stores: {
      steam: { url: steamUrl(632360) },
      epic: { url: epicUrl("risk-of-rain-2") },
    },
    communityRating: 4.6,
    ratingCount: 45700,
  },
  {
    id: "halflife",
    slug: "half-life",
    title: "Half-Life",
    year: 1998,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Sci-Fi", "Action"],
    tags: ["Classic", "Story Rich", "Influential"],
    description:
      "The shooter that proved a story could unfold entirely in first person without a single cutscene. Still the blueprint decades later.",
    cover: steamCover(70),
    backdrop: steamBackdrop(70),
    stores: { steam: { url: steamUrl(70) } },
    communityRating: 4.7,
    ratingCount: 61200,
  },
  {
    id: "doom1993",
    slug: "doom",
    title: "DOOM (1993)",
    year: 1993,
    developer: "id Software",
    publisher: "Bethesda Softworks",
    genres: ["Shooter", "Action", "Classic"],
    tags: ["Retro", "Fast-Paced", "Influential"],
    description:
      "The original. A marine, a shotgun, and hell itself — the game that defined the first-person shooter for the next thirty years.",
    cover: steamCover(2280),
    backdrop: steamBackdrop(2280),
    stores: {
      steam: { url: steamUrl(2280) },
      gog: { url: gogUrl("doom") },
    },
    communityRating: 4.7,
    ratingCount: 38900,
  },
  {
    id: "fallout1",
    slug: "fallout",
    title: "Fallout",
    year: 1997,
    developer: "Interplay Entertainment",
    publisher: "Interplay Entertainment",
    genres: ["RPG", "Strategy", "Classic"],
    tags: ["Post-Apocalyptic", "Turn-Based", "Retro"],
    description:
      "The original post-nuclear RPG — grim, funny, and unforgiving in ways the modern series softened. Still holds up as writing.",
    cover: steamCover(38400),
    backdrop: steamBackdrop(38400),
    stores: {
      steam: { url: steamUrl(38400) },
      gog: { url: gogUrl("fallout") },
    },
    communityRating: 4.5,
    ratingCount: 15200,
  },
  {
    id: "fallout2",
    slug: "fallout-2",
    title: "Fallout 2",
    year: 1998,
    developer: "Black Isle Studios",
    publisher: "Interplay Entertainment",
    genres: ["RPG", "Strategy", "Classic"],
    tags: ["Post-Apocalyptic", "Turn-Based", "Retro"],
    description:
      "Bigger, weirder and even more reactive than the original. A high point for choice-and-consequence RPG design.",
    cover: steamCover(38410),
    backdrop: steamBackdrop(38410),
    stores: {
      steam: { url: steamUrl(38410) },
      gog: { url: gogUrl("fallout_2") },
    },
    communityRating: 4.5,
    ratingCount: 13800,
  },
  {
    id: "falloutnv",
    slug: "fallout-new-vegas",
    title: "Fallout: New Vegas",
    year: 2010,
    developer: "Obsidian Entertainment",
    publisher: "Bethesda Softworks",
    genres: ["RPG", "Open World", "Post-Apocalyptic"],
    tags: ["Faction Politics", "Story Rich", "Classic"],
    description:
      "Obsidian's take on the Mojave Wasteland, with faction writing and reactivity the mainline games have never quite matched.",
    cover: steamCover(22380),
    backdrop: steamBackdrop(22380),
    stores: {
      steam: { url: steamUrl(22380) },
      gog: { url: gogUrl("fallout_new_vegas") },
    },
    communityRating: 4.7,
    ratingCount: 74300,
  },
  {
    id: "fallout3",
    slug: "fallout-3",
    title: "Fallout 3",
    year: 2008,
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genres: ["RPG", "Open World", "Post-Apocalyptic"],
    tags: ["Exploration", "Story Rich", "Classic"],
    description:
      "The series' jump to open-world 3D, trading the isometric view for a ruined Capital Wasteland worth getting lost in.",
    cover: steamCover(22300),
    backdrop: steamBackdrop(22300),
    stores: {
      steam: { url: steamUrl(22300) },
      gog: { url: gogUrl("fallout_3_game_of_the_year_edition") },
    },
    communityRating: 4.5,
    ratingCount: 58600,
  },
  {
    id: "skyrim",
    slug: "the-elder-scrolls-v-skyrim",
    title: "The Elder Scrolls V: Skyrim",
    year: 2011,
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genres: ["RPG", "Open World", "Fantasy"],
    tags: ["Dragons", "Moddable", "Classic"],
    description:
      "Still one of the most modded games ever made. A decade-plus later, people are still finding new ways to disappear into it.",
    cover: steamCover(72850),
    backdrop: steamBackdrop(72850),
    stores: { steam: { url: steamUrl(72850) } },
    communityRating: 4.6,
    ratingCount: 187400,
  },
  {
    id: "bgee",
    slug: "baldurs-gate-enhanced-edition",
    title: "Baldur's Gate: Enhanced Edition",
    year: 1998,
    developer: "BioWare / Beamdog",
    publisher: "Beamdog",
    genres: ["RPG", "Fantasy", "Classic"],
    tags: ["Party-Based", "D&D", "Retro"],
    description:
      "The party-based RPG that helped invent the modern CRPG, cleaned up and re-released for a new generation.",
    cover: steamCover(228280),
    backdrop: steamBackdrop(228280),
    stores: {
      steam: { url: steamUrl(228280) },
      gog: { url: gogUrl("baldurs_gate_enhanced_edition") },
    },
    communityRating: 4.4,
    ratingCount: 21300,
  },
  {
    id: "systemshock2",
    slug: "system-shock-2",
    title: "System Shock 2",
    year: 1999,
    developer: "Looking Glass Studios",
    publisher: "Nightdive Studios",
    genres: ["Shooter", "RPG", "Horror"],
    tags: ["Immersive Sim", "Sci-Fi", "Classic"],
    description:
      "The template for the immersive sim RPG-shooter hybrid, and still one of gaming's best villains in SHODAN.",
    cover: steamCover(238210),
    backdrop: steamBackdrop(238210),
    stores: {
      steam: { url: steamUrl(238210) },
      gog: { url: gogUrl("system_shock_2") },
    },
    communityRating: 4.6,
    ratingCount: 17800,
  },
  {
    id: "deusex",
    slug: "deus-ex-goty",
    title: "Deus Ex",
    year: 2000,
    developer: "Ion Storm",
    publisher: "Square Enix",
    genres: ["RPG", "Shooter", "Sci-Fi"],
    tags: ["Immersive Sim", "Cyberpunk", "Classic"],
    description:
      "A conspiracy-thriller immersive sim where almost every room has three ways through it. Aged better than games half its age.",
    cover: steamCover(6910),
    backdrop: steamBackdrop(6910),
    stores: {
      steam: { url: steamUrl(6910) },
      gog: { url: gogUrl("deus_ex_game_of_the_year_edition") },
    },
    communityRating: 4.6,
    ratingCount: 22900,
  },
  {
    id: "grimfandango",
    slug: "grim-fandango-remastered",
    title: "Grim Fandango Remastered",
    year: 1998,
    developer: "Double Fine Productions",
    publisher: "Double Fine Productions",
    genres: ["Adventure", "Puzzle", "Classic"],
    tags: ["Point-and-Click", "Noir", "Story Rich"],
    description:
      "A film-noir detective story set in the Land of the Dead. Tim Schafer's best-written adventure game, remastered and still sharp.",
    cover: steamCover(316790),
    backdrop: steamBackdrop(316790),
    stores: {
      steam: { url: steamUrl(316790) },
      gog: { url: gogUrl("grim_fandango_remastered") },
    },
    communityRating: 4.5,
    ratingCount: 9200,
  },
  {
    id: "amnesia",
    slug: "amnesia-the-dark-descent",
    title: "Amnesia: The Dark Descent",
    year: 2010,
    developer: "Frictional Games",
    publisher: "Frictional Games",
    genres: ["Horror", "Puzzle", "Indie"],
    tags: ["Atmospheric", "No Combat", "Classic"],
    description:
      "The game that redefined horror for a generation of streamers — no weapons, just a lantern, sanity, and things in the dark.",
    cover: steamCover(57300),
    backdrop: steamBackdrop(57300),
    stores: {
      steam: { url: steamUrl(57300) },
      gog: { url: gogUrl("amnesia_the_dark_descent") },
    },
    communityRating: 4.4,
    ratingCount: 31200,
  },
  {
    id: "bioshock",
    slug: "bioshock",
    title: "BioShock",
    year: 2007,
    developer: "2K Boston / Irrational Games",
    publisher: "2K",
    genres: ["Shooter", "RPG", "Sci-Fi"],
    tags: ["Story Rich", "Atmospheric", "Classic"],
    description:
      "Welcome to Rapture. A shooter with a philosophy essay hidden inside it, and one of gaming's most-quoted twists.",
    cover: steamCover(7670),
    backdrop: steamBackdrop(7670),
    stores: { steam: { url: steamUrl(7670) } },
    communityRating: 4.6,
    ratingCount: 42100,
  },
  {
    id: "dragonageorigins",
    slug: "dragon-age-origins",
    title: "Dragon Age: Origins",
    year: 2009,
    developer: "BioWare",
    publisher: "Electronic Arts",
    genres: ["RPG", "Fantasy", "Classic"],
    tags: ["Party-Based", "Story Rich", "Dark Fantasy"],
    description:
      "BioWare's darkest fantasy RPG — grim, political, and packed with companions people still argue about years later.",
    cover: steamCover(47810),
    backdrop: steamBackdrop(47810),
    stores: { steam: { url: steamUrl(47810) } },
    communityRating: 4.5,
    ratingCount: 28700,
  },
  {
    id: "dishonored",
    slug: "dishonored",
    title: "Dishonored",
    year: 2012,
    developer: "Arkane Studios",
    publisher: "Bethesda Softworks",
    genres: ["Action", "Stealth", "Immersive Sim"],
    tags: ["Supernatural", "Choice-Driven", "Atmospheric"],
    description:
      "A plague-ridden, whale-oil-powered city and a supernatural assassin who can blink across rooftops. Play it loud or ghost it silent.",
    cover: steamCover(205100),
    backdrop: steamBackdrop(205100),
    stores: { steam: { url: steamUrl(205100) } },
    communityRating: 4.5,
    ratingCount: 25400,
  },
  {
    id: "horizonzerodawn",
    slug: "horizon-zero-dawn",
    title: "Horizon Zero Dawn",
    year: 2017,
    developer: "Guerrilla Games",
    publisher: "PlayStation PC LLC",
    genres: ["Open World", "RPG", "Sci-Fi"],
    tags: ["Robot Dinosaurs", "Story Rich", "Exploration"],
    description:
      "Hunt robot dinosaurs across a beautiful post-post-apocalyptic Earth. The mystery of what came before carries the whole game.",
    cover: steamCover(1151640),
    backdrop: steamBackdrop(1151640),
    stores: { steam: { url: steamUrl(1151640) } },
    communityRating: 4.5,
    ratingCount: 68900,
  },
  {
    id: "nierautomata",
    slug: "nier-automata",
    title: "NieR: Automata",
    year: 2017,
    developer: "PlatinumGames",
    publisher: "Square Enix",
    genres: ["Action", "RPG", "Sci-Fi"],
    tags: ["Multiple Endings", "Philosophical", "Story Rich"],
    description:
      "An android action-RPG that asks you to finish it three times before it tells you what it's actually about. Worth every playthrough.",
    cover: steamCover(524220),
    backdrop: steamBackdrop(524220),
    stores: { steam: { url: steamUrl(524220) } },
    communityRating: 4.7,
    ratingCount: 71300,
  },
  {
    id: "re4remake",
    slug: "resident-evil-4",
    title: "Resident Evil 4",
    year: 2023,
    developer: "Capcom",
    publisher: "Capcom",
    genres: ["Horror", "Shooter", "Action"],
    tags: ["Survival Horror", "Remake", "Third-Person"],
    description:
      "A ground-up remake of the game that reinvented survival horror, and somehow it works just as well the second time.",
    cover: steamCover(2050650),
    backdrop: steamBackdrop(2050650),
    stores: { steam: { url: steamUrl(2050650) } },
    communityRating: 4.8,
    ratingCount: 89200,
  },
  {
    id: "revillage",
    slug: "resident-evil-village",
    title: "Resident Evil Village",
    year: 2021,
    developer: "Capcom",
    publisher: "Capcom",
    genres: ["Horror", "Shooter", "Action"],
    tags: ["Survival Horror", "First-Person", "Gothic"],
    description:
      "A gothic horror village full of monsters, one very tall vampire, and a first-person perspective that makes every corner tense.",
    cover: steamCover(1196590),
    backdrop: steamBackdrop(1196590),
    stores: { steam: { url: steamUrl(1196590) } },
    communityRating: 4.6,
    ratingCount: 62700,
  },
  {
    id: "alanwake2",
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    year: 2023,
    developer: "Remedy Entertainment",
    publisher: "Epic Games Publishing",
    genres: ["Horror", "Narrative", "Action"],
    tags: ["Survival Horror", "Atmospheric", "Story Rich"],
    description:
      "Remedy's most confident game yet — a horror sequel that splits between two investigators and bends reality around live-action segments.",
    cover: steamCover(1946460),
    backdrop: steamBackdrop(1946460),
    stores: {
      steam: { url: steamUrl(1946460) },
      epic: { url: epicUrl("alan-wake-2") },
    },
    communityRating: 4.7,
    ratingCount: 24600,
  },
  {
    id: "seaofthieves",
    slug: "sea-of-thieves",
    title: "Sea of Thieves",
    year: 2018,
    developer: "Rare",
    publisher: "Xbox Game Studios",
    genres: ["Adventure", "Multiplayer", "Pirates"],
    tags: ["Co-op", "Open World", "PvP"],
    description:
      "A crewed-up pirate sandbox where the best stories come from things nobody scripted. Better with three friends and a bad plan.",
    cover: steamCover(1172620),
    backdrop: steamBackdrop(1172620),
    stores: { steam: { url: steamUrl(1172620) } },
    communityRating: 4.3,
    ratingCount: 51200,
  },
  {
    id: "valheim",
    slug: "valheim",
    title: "Valheim",
    year: 2021,
    developer: "Iron Gate AB",
    publisher: "Coffee Stain Publishing",
    genres: ["Survival", "Open World", "Co-op"],
    tags: ["Viking", "Crafting", "Building"],
    description:
      "A Viking-purgatory survival game that turned base-building into an art form, best played with a small crew over many weekends.",
    cover: steamCover(892970),
    backdrop: steamBackdrop(892970),
    stores: { steam: { url: steamUrl(892970) } },
    communityRating: 4.6,
    ratingCount: 96300,
  },
  {
    id: "palworld",
    slug: "palworld",
    title: "Palworld",
    year: 2024,
    developer: "Pocketpair",
    publisher: "Pocketpair",
    genres: ["Survival", "Open World", "Crafting"],
    tags: ["Creature Collecting", "Co-op", "Multiplayer"],
    description:
      "Pokémon-adjacent creature collecting crossed with a base-building survival game, complete with put-them-to-work factory chains.",
    cover: steamCover(1623730),
    backdrop: steamBackdrop(1623730),
    stores: { steam: { url: steamUrl(1623730) } },
    communityRating: 4.3,
    ratingCount: 58400,
  },
  {
    id: "lethalcompany",
    slug: "lethal-company",
    title: "Lethal Company",
    year: 2023,
    developer: "Zeekerss",
    publisher: "Zeekerss",
    genres: ["Horror", "Co-op", "Indie"],
    tags: ["Multiplayer", "Comedy Horror", "Cheap"],
    description:
      "A four-player scavenging horror game where the real threat is usually your own teammates' decision-making.",
    cover: steamCover(1966720),
    backdrop: steamBackdrop(1966720),
    stores: { steam: { url: steamUrl(1966720) } },
    communityRating: 4.6,
    ratingCount: 33100,
  },
  {
    id: "helldivers2",
    slug: "helldivers-2",
    title: "Helldivers 2",
    year: 2024,
    developer: "Arrowhead Game Studios",
    publisher: "PlayStation PC LLC",
    genres: ["Shooter", "Co-op", "Sci-Fi"],
    tags: ["Satire", "Third-Person", "Multiplayer"],
    description:
      "Democracy-flavored bug and robot extermination with friendly fire always on. The satire is the point, not a side dish.",
    cover: steamCover(553850),
    backdrop: steamBackdrop(553850),
    stores: { steam: { url: steamUrl(553850) } },
    communityRating: 4.5,
    ratingCount: 47800,
  },
  {
    id: "awayout",
    slug: "a-way-out",
    title: "A Way Out",
    year: 2018,
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    genres: ["Action", "Adventure", "Co-op"],
    tags: ["Co-op Only", "Split-Screen", "Story Rich"],
    description:
      "A two-player-only prison break story, split-screen throughout, from the studio that later made It Takes Two.",
    cover: steamCover(1222700),
    backdrop: steamBackdrop(1222700),
    stores: { steam: { url: steamUrl(1222700) } },
    communityRating: 4.4,
    ratingCount: 15600,
  },
  {
    id: "deeprockgalactic",
    slug: "deep-rock-galactic",
    title: "Deep Rock Galactic",
    year: 2020,
    developer: "Ghost Ship Games",
    publisher: "Coffee Stain Publishing",
    genres: ["Shooter", "Co-op", "Sci-Fi"],
    tags: ["Space Dwarves", "Mining", "Multiplayer"],
    description:
      "Four dwarves, procedurally destructible caves, and a mining quota. Rock and stone, as the saying goes.",
    cover: steamCover(548430),
    backdrop: steamBackdrop(548430),
    stores: { steam: { url: steamUrl(548430) } },
    communityRating: 4.8,
    ratingCount: 62100,
  },
  {
    id: "monsterhunterworld",
    slug: "monster-hunter-world",
    title: "Monster Hunter: World",
    year: 2018,
    developer: "Capcom",
    publisher: "Capcom",
    genres: ["Action", "RPG", "Co-op"],
    tags: ["Boss Hunting", "Crafting", "Multiplayer"],
    description:
      "The entry that brought monster hunting to a global audience — huge beasts, deep gear-crafting loops, and endgame that never really ends.",
    cover: steamCover(582010),
    backdrop: steamBackdrop(582010),
    stores: { steam: { url: steamUrl(582010) } },
    communityRating: 4.6,
    ratingCount: 84500,
  },
  {
    id: "monsterhunterrise",
    slug: "monster-hunter-rise",
    title: "Monster Hunter Rise",
    year: 2021,
    developer: "Capcom",
    publisher: "Capcom",
    genres: ["Action", "RPG", "Co-op"],
    tags: ["Boss Hunting", "Crafting", "Multiplayer"],
    description:
      "Faster and more mobile than World, with a grappling-hook companion that turns every hunt into an aerial assault.",
    cover: steamCover(1446780),
    backdrop: steamBackdrop(1446780),
    stores: { steam: { url: steamUrl(1446780) } },
    communityRating: 4.5,
    ratingCount: 41200,
  },
  {
    id: "dyinglight2",
    slug: "dying-light-2",
    title: "Dying Light 2",
    year: 2022,
    developer: "Techland",
    publisher: "Techland",
    genres: ["Open World", "Horror", "Action"],
    tags: ["Parkour", "Zombies", "Co-op"],
    description:
      "Zombie-parkour across a vertical city where the real skill tree is learning to run instead of fight.",
    cover: steamCover(534380),
    backdrop: steamBackdrop(534380),
    stores: { steam: { url: steamUrl(534380) } },
    communityRating: 4.3,
    ratingCount: 39700,
  },
  {
    id: "nomanssky",
    slug: "no-mans-sky",
    title: "No Man's Sky",
    year: 2016,
    developer: "Hello Games",
    publisher: "Hello Games",
    genres: ["Survival", "Open World", "Sci-Fi"],
    tags: ["Space Exploration", "Crafting", "Redemption Story"],
    description:
      "Famously rough at launch, and just as famously rebuilt into one of the most generous, content-packed space sims around — still free updates today.",
    cover: steamCover(275850),
    backdrop: steamBackdrop(275850),
    stores: {
      steam: { url: steamUrl(275850) },
      gog: { url: gogUrl("no_mans_sky") },
      epic: { url: epicUrl("no-mans-sky") },
    },
    communityRating: 4.4,
    ratingCount: 91400,
  },
  {
    id: "raft",
    slug: "raft",
    title: "Raft",
    year: 2022,
    developer: "Redbeet Interactive",
    publisher: "Axolot Games",
    genres: ["Survival", "Crafting", "Co-op"],
    tags: ["Ocean", "Building", "Multiplayer"],
    description:
      "Survive on an ever-growing raft, hook floating debris, and try not to think too hard about what's circling underneath.",
    cover: steamCover(648800),
    backdrop: steamBackdrop(648800),
    stores: { steam: { url: steamUrl(648800) } },
    communityRating: 4.5,
    ratingCount: 28300,
  },
  {
    id: "theforest",
    slug: "the-forest",
    title: "The Forest",
    year: 2018,
    developer: "Endnight Games",
    publisher: "Endnight Games",
    genres: ["Survival", "Horror", "Open World"],
    tags: ["Crafting", "Cannibals", "Co-op"],
    description:
      "Crash-land, build a base, and try to survive a forest full of things that are absolutely not okay with you being there.",
    cover: steamCover(242760),
    backdrop: steamBackdrop(242760),
    stores: { steam: { url: steamUrl(242760) } },
    communityRating: 4.6,
    ratingCount: 44700,
  },
  {
    id: "sonsoftheforest",
    slug: "sons-of-the-forest",
    title: "Sons of the Forest",
    year: 2023,
    developer: "Endnight Games",
    publisher: "Endnight Games",
    genres: ["Survival", "Horror", "Open World"],
    tags: ["Crafting", "Cannibals", "Co-op"],
    description:
      "The sequel goes bigger and scarier, with smarter enemies and a survival loop that's easy to lose entire nights to.",
    cover: steamCover(1326470),
    backdrop: steamBackdrop(1326470),
    stores: { steam: { url: steamUrl(1326470) } },
    communityRating: 4.5,
    ratingCount: 51900,
  },
  {
    id: "dontstarvetogether",
    slug: "dont-starve-together",
    title: "Don't Starve Together",
    year: 2016,
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    genres: ["Survival", "Co-op", "Indie"],
    tags: ["Gothic Art", "Crafting", "Multiplayer"],
    description:
      "The co-op version of Klei's gothic survival game — punishing, stylish, and always one bad decision away from disaster.",
    cover: steamCover(322330),
    backdrop: steamBackdrop(322330),
    stores: {
      steam: { url: steamUrl(322330) },
      gog: { url: gogUrl("dont_starve_together") },
    },
    communityRating: 4.6,
    ratingCount: 37800,
  },
  {
    id: "dontstarve",
    slug: "dont-starve",
    title: "Don't Starve",
    year: 2013,
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    genres: ["Survival", "Indie", "Roguelike"],
    tags: ["Gothic Art", "Crafting", "Difficult"],
    description:
      "The solo original — a gothic wilderness survival game where the art style does as much work as the mechanics.",
    cover: steamCover(219740),
    backdrop: steamBackdrop(219740),
    stores: {
      steam: { url: steamUrl(219740) },
      gog: { url: gogUrl("dont_starve") },
    },
    communityRating: 4.6,
    ratingCount: 29400,
  },
  {
    id: "rimworld",
    slug: "rimworld",
    title: "RimWorld",
    year: 2018,
    developer: "Ludeon Studios",
    publisher: "Ludeon Studios",
    genres: ["Strategy", "Simulation", "Sci-Fi"],
    tags: ["Colony Sim", "Procedural Stories", "Deep"],
    description:
      "A colony sim that writes its own tragedies — the AI storyteller has ended more colonies than any raid ever could.",
    cover: steamCover(294100),
    backdrop: steamBackdrop(294100),
    stores: {
      steam: { url: steamUrl(294100) },
      gog: { url: gogUrl("rimworld") },
    },
    communityRating: 4.8,
    ratingCount: 67200,
  },
  {
    id: "factorio",
    slug: "factorio",
    title: "Factorio",
    year: 2020,
    developer: "Wube Software",
    publisher: "Wube Software",
    genres: ["Strategy", "Simulation", "Sandbox"],
    tags: ["Automation", "Factory Building", "Addictive"],
    description:
      "The factory must grow. A logistics-automation game so deep it comes with its own warning label about lost sleep.",
    cover: steamCover(427520),
    backdrop: steamBackdrop(427520),
    stores: {
      steam: { url: steamUrl(427520) },
      gog: { url: gogUrl("factorio") },
    },
    communityRating: 4.9,
    ratingCount: 55600,
  },
  {
    id: "satisfactory",
    slug: "satisfactory",
    title: "Satisfactory",
    year: 2024,
    developer: "Coffee Stain Studios",
    publisher: "Coffee Stain Publishing",
    genres: ["Strategy", "Simulation", "Open World"],
    tags: ["Automation", "Factory Building", "First-Person"],
    description:
      "Factorio in first-person 3D, on an alien planet, with belts you can ride. Just as capable of eating your weekend.",
    cover: steamCover(526870),
    backdrop: steamBackdrop(526870),
    stores: {
      steam: { url: steamUrl(526870) },
      epic: { url: epicUrl("satisfactory") },
    },
    communityRating: 4.8,
    ratingCount: 34200,
  },
  {
    id: "oxygennotincluded",
    slug: "oxygen-not-included",
    title: "Oxygen Not Included",
    year: 2019,
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    genres: ["Simulation", "Strategy", "Indie"],
    tags: ["Colony Sim", "Physics", "Difficult"],
    description:
      "A space-colony survival sim built on thermodynamics and gas simulation. Beautiful, brutal, and extremely nerdy in the best way.",
    cover: steamCover(457140),
    backdrop: steamBackdrop(457140),
    stores: { steam: { url: steamUrl(457140) } },
    communityRating: 4.7,
    ratingCount: 26100,
  },
  {
    id: "kerbalspaceprogram",
    slug: "kerbal-space-program",
    title: "Kerbal Space Program",
    year: 2015,
    developer: "Squad",
    publisher: "Private Division",
    genres: ["Simulation", "Strategy", "Space"],
    tags: ["Rocket Science", "Sandbox", "Physics"],
    description:
      "Design, launch, and inevitably explode rockets crewed by little green astronauts. Teaches real orbital mechanics by accident.",
    cover: steamCover(220200),
    backdrop: steamBackdrop(220200),
    stores: {
      steam: { url: steamUrl(220200) },
      gog: { url: gogUrl("kerbal_space_program") },
    },
    communityRating: 4.6,
    ratingCount: 32800,
  },
  {
    id: "citiesskylines",
    slug: "cities-skylines",
    title: "Cities: Skylines",
    year: 2015,
    developer: "Colossal Order",
    publisher: "Paradox Interactive",
    genres: ["Simulation", "Strategy", "City Builder"],
    tags: ["Traffic", "Moddable", "Deep"],
    description:
      "The city builder that finally got traffic simulation right, with a modding scene that's kept it relevant for a decade.",
    cover: steamCover(255710),
    backdrop: steamBackdrop(255710),
    stores: {
      steam: { url: steamUrl(255710) },
      gog: { url: gogUrl("cities_skylines") },
    },
    communityRating: 4.7,
    ratingCount: 79400,
  },
  {
    id: "citiesskylines2",
    slug: "cities-skylines-2",
    title: "Cities: Skylines II",
    year: 2023,
    developer: "Colossal Order",
    publisher: "Paradox Interactive",
    genres: ["Simulation", "Strategy", "City Builder"],
    tags: ["Traffic", "Economy", "Deep"],
    description:
      "A more ambitious, more demanding sequel — deeper economic simulation, at the cost of a rockier launch than its predecessor.",
    cover: steamCover(949230),
    backdrop: steamBackdrop(949230),
    stores: { steam: { url: steamUrl(949230) } },
    communityRating: 3.6,
    ratingCount: 22700,
  },
  {
    id: "frostpunk",
    slug: "frostpunk",
    title: "Frostpunk",
    year: 2018,
    developer: "11 bit studios",
    publisher: "11 bit studios",
    genres: ["Strategy", "Simulation", "Survival"],
    tags: ["Moral Choices", "City Builder", "Bleak"],
    description:
      "A city-survival strategy game about the compromises you make to keep people alive in an endless frost. The choices linger.",
    cover: steamCover(323190),
    backdrop: steamBackdrop(323190),
    stores: {
      steam: { url: steamUrl(323190) },
      gog: { url: gogUrl("frostpunk") },
    },
    communityRating: 4.7,
    ratingCount: 41300,
  },
  {
    id: "frostpunk2",
    slug: "frostpunk-2",
    title: "Frostpunk 2",
    year: 2024,
    developer: "11 bit studios",
    publisher: "11 bit studios",
    genres: ["Strategy", "Simulation", "Survival"],
    tags: ["Politics", "City Builder", "Bleak"],
    description:
      "Trades individual survival for city-scale politics — factions, votes, and the same knack for making every decision hurt.",
    cover: steamCover(1601580),
    backdrop: steamBackdrop(1601580),
    stores: { steam: { url: steamUrl(1601580) } },
    communityRating: 4.3,
    ratingCount: 14800,
  },
  {
    id: "twopointhospital",
    slug: "two-point-hospital",
    title: "Two Point Hospital",
    year: 2018,
    developer: "Two Point Studios",
    publisher: "Sega",
    genres: ["Simulation", "Strategy", "Comedy"],
    tags: ["Management", "British Humor", "Sandbox"],
    description:
      "The spiritual successor to Theme Hospital — build absurd hospitals, treat absurd illnesses, laugh at the patient names.",
    cover: steamCover(535930),
    backdrop: steamBackdrop(535930),
    stores: {
      steam: { url: steamUrl(535930) },
      gog: { url: gogUrl("two_point_hospital") },
      epic: { url: epicUrl("two-point-hospital") },
    },
    communityRating: 4.5,
    ratingCount: 19600,
  },
  {
    id: "planetcoaster",
    slug: "planet-coaster",
    title: "Planet Coaster",
    year: 2016,
    developer: "Frontier Developments",
    publisher: "Frontier Developments",
    genres: ["Simulation", "Strategy", "Management"],
    tags: ["Theme Park", "Sandbox", "Creative"],
    description:
      "The modern RollerCoaster Tycoon successor, with a piece-by-piece builder that turned theme-park design into its own art form.",
    cover: steamCover(493340),
    backdrop: steamBackdrop(493340),
    stores: { steam: { url: steamUrl(493340) } },
    communityRating: 4.6,
    ratingCount: 28900,
  },
  {
    id: "totalwarwarhammer3",
    slug: "total-war-warhammer-iii",
    title: "Total War: WARHAMMER III",
    year: 2022,
    developer: "Creative Assembly",
    publisher: "Sega",
    genres: ["Strategy", "Fantasy", "War"],
    tags: ["Turn-Based", "Real-Time Battles", "Deep"],
    description:
      "The trilogy's finale — massive turn-based campaign map, real-time battles with thousands of units, and a roster of increasingly unhinged factions.",
    cover: steamCover(1142710),
    backdrop: steamBackdrop(1142710),
    stores: { steam: { url: steamUrl(1142710) } },
    communityRating: 4.4,
    ratingCount: 31600,
  },
  {
    id: "crusaderkings3",
    slug: "crusader-kings-iii",
    title: "Crusader Kings III",
    year: 2020,
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    genres: ["Strategy", "RPG", "Historical"],
    tags: ["Dynasty", "Politics", "Deep"],
    description:
      "A medieval dynasty simulator that's less about armies and more about scheming, marriages, and generational grudges.",
    cover: steamCover(1158310),
    backdrop: steamBackdrop(1158310),
    stores: {
      steam: { url: steamUrl(1158310) },
      gog: { url: gogUrl("crusader_kings_iii") },
    },
    communityRating: 4.6,
    ratingCount: 24300,
  },
  {
    id: "eu4",
    slug: "europa-universalis-iv",
    title: "Europa Universalis IV",
    year: 2013,
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    genres: ["Strategy", "Historical", "Grand Strategy"],
    tags: ["Nation Building", "Deep", "Moddable"],
    description:
      "Take any nation from 1444 onward and reshape the map. A decade of DLC has made it one of the deepest strategy games ever released.",
    cover: steamCover(236850),
    backdrop: steamBackdrop(236850),
    stores: {
      steam: { url: steamUrl(236850) },
      gog: { url: gogUrl("europa_universalis_iv") },
    },
    communityRating: 4.5,
    ratingCount: 33900,
  },
  {
    id: "civ6",
    slug: "sid-meiers-civilization-vi",
    title: "Sid Meier's Civilization VI",
    year: 2016,
    developer: "Firaxis Games",
    publisher: "2K",
    genres: ["Strategy", "Turn-Based", "Historical"],
    tags: ["4X", "One More Turn", "Deep"],
    description:
      "Build an empire from the Stone Age to space flight. The genre-defining \"one more turn\" game, still going strong.",
    cover: steamCover(289070),
    backdrop: steamBackdrop(289070),
    stores: {
      steam: { url: steamUrl(289070) },
      epic: { url: epicUrl("sid-meiers-civilization-vi") },
    },
    communityRating: 4.6,
    ratingCount: 71200,
  },
  {
    id: "xcom2",
    slug: "xcom-2",
    title: "XCOM 2",
    year: 2016,
    developer: "Firaxis Games",
    publisher: "2K",
    genres: ["Strategy", "Turn-Based", "Sci-Fi"],
    tags: ["Tactics", "Permadeath", "Difficult"],
    description:
      "Turn-based tactical combat where every mission can go wrong in an instant, and every lost soldier actually hurts.",
    cover: steamCover(268500),
    backdrop: steamBackdrop(268500),
    stores: { steam: { url: steamUrl(268500) } },
    communityRating: 4.6,
    ratingCount: 45700,
  },
  {
    id: "intothebreach",
    slug: "into-the-breach",
    title: "Into the Breach",
    year: 2018,
    developer: "Subset Games",
    publisher: "Subset Games",
    genres: ["Strategy", "Turn-Based", "Roguelike"],
    tags: ["Puzzle-Like", "Mechs", "Tight Design"],
    description:
      "Perfect-information tactics on tiny grids — every move is knowable in advance, and every failure is entirely your own fault.",
    cover: steamCover(590380),
    backdrop: steamBackdrop(590380),
    stores: {
      steam: { url: steamUrl(590380) },
      gog: { url: gogUrl("into_the_breach") },
      epic: { url: epicUrl("into-the-breach") },
    },
    communityRating: 4.8,
    ratingCount: 22400,
  },
  {
    id: "darkestdungeon",
    slug: "darkest-dungeon",
    title: "Darkest Dungeon",
    year: 2016,
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    genres: ["RPG", "Roguelike", "Strategy"],
    tags: ["Turn-Based", "Stress Mechanic", "Gothic"],
    description:
      "A gothic dungeon-crawler where managing your party's sanity matters as much as their health bars. Ruthless and gorgeous.",
    cover: steamCover(262060),
    backdrop: steamBackdrop(262060),
    stores: {
      steam: { url: steamUrl(262060) },
      gog: { url: gogUrl("darkest_dungeon") },
      epic: { url: epicUrl("darkest-dungeon") },
    },
    communityRating: 4.6,
    ratingCount: 51800,
  },
  {
    id: "darkestdungeon2",
    slug: "darkest-dungeon-2",
    title: "Darkest Dungeon II",
    year: 2023,
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    genres: ["RPG", "Roguelike", "Strategy"],
    tags: ["Turn-Based", "Stress Mechanic", "Gothic"],
    description:
      "A stagecoach replaces the hamlet — a roguelike restructuring of the original's stress-and-sanity formula, run to run.",
    cover: steamCover(1940340),
    backdrop: steamBackdrop(1940340),
    stores: {
      steam: { url: steamUrl(1940340) },
      epic: { url: epicUrl("darkest-dungeon-ii") },
    },
    communityRating: 4.1,
    ratingCount: 12300,
  },
  {
    id: "ftl",
    slug: "ftl-faster-than-light",
    title: "FTL: Faster Than Light",
    year: 2012,
    developer: "Subset Games",
    publisher: "Subset Games",
    genres: ["Strategy", "Roguelike", "Simulation"],
    tags: ["Spaceship Management", "Real-Time", "Difficult"],
    description:
      "The roguelike that launched a thousand roguelikes. Manage a spaceship crew one crisis at a time, permadeath included.",
    cover: steamCover(212680),
    backdrop: steamBackdrop(212680),
    stores: {
      steam: { url: steamUrl(212680) },
      gog: { url: gogUrl("ftl_faster_than_light") },
    },
    communityRating: 4.7,
    ratingCount: 38200,
  },
  {
    id: "enterthegungeon",
    slug: "enter-the-gungeon",
    title: "Enter the Gungeon",
    year: 2016,
    developer: "Dodge Roll",
    publisher: "Devolver Digital",
    genres: ["Roguelike", "Shooter", "Indie"],
    tags: ["Bullet Hell", "Co-op", "Pixel Art"],
    description:
      "A bullet-hell dungeon crawler about guns that shoot guns. Punishingly precise and endlessly quotable.",
    cover: steamCover(311690),
    backdrop: steamBackdrop(311690),
    stores: {
      steam: { url: steamUrl(311690) },
      gog: { url: gogUrl("enter_the_gungeon") },
      epic: { url: epicUrl("enter-the-gungeon") },
    },
    communityRating: 4.6,
    ratingCount: 34500,
  },
  {
    id: "nuclearthrone",
    slug: "nuclear-throne",
    title: "Nuclear Throne",
    year: 2015,
    developer: "Vlambeer",
    publisher: "Vlambeer",
    genres: ["Roguelike", "Shooter", "Indie"],
    tags: ["Top-Down", "Pixel Art", "Fast-Paced"],
    description:
      "A ruthless top-down roguelike shooter from the studio behind Nuclear Throne's own legend of relentless difficulty and speed.",
    cover: steamCover(242680),
    backdrop: steamBackdrop(242680),
    stores: {
      steam: { url: steamUrl(242680) },
      gog: { url: gogUrl("nuclear_throne") },
    },
    communityRating: 4.5,
    ratingCount: 18700,
  },
  {
    id: "spelunky2",
    slug: "spelunky-2",
    title: "Spelunky 2",
    year: 2020,
    developer: "Mossmouth",
    publisher: "Mossmouth",
    genres: ["Roguelike", "Platformer", "Indie"],
    tags: ["Procedural", "Difficult", "Deep Systems"],
    description:
      "A cave-diving platformer roguelike with emergent systems so deep speedrunners are still finding new tech years later.",
    cover: steamCover(418530),
    backdrop: steamBackdrop(418530),
    stores: { steam: { url: steamUrl(418530) } },
    communityRating: 4.5,
    ratingCount: 14900,
  },
  {
    id: "moonlighter",
    slug: "moonlighter",
    title: "Moonlighter",
    year: 2018,
    developer: "Digital Sun",
    publisher: "11 bit studios",
    genres: ["RPG", "Roguelike", "Indie"],
    tags: ["Shopkeeper", "Dungeon Crawling", "Pixel Art"],
    description:
      "Run a shop by day, raid procedural dungeons by night, and set your own prices for the loot you drag back.",
    cover: steamCover(606150),
    backdrop: steamBackdrop(606150),
    stores: {
      steam: { url: steamUrl(606150) },
      gog: { url: gogUrl("moonlighter") },
      epic: { url: epicUrl("moonlighter") },
    },
    communityRating: 4.4,
    ratingCount: 13200,
  },
  {
    id: "shovelknight",
    slug: "shovel-knight-treasure-trove",
    title: "Shovel Knight: Treasure Trove",
    year: 2014,
    developer: "Yacht Club Games",
    publisher: "Yacht Club Games",
    genres: ["Platformer", "Action", "Retro"],
    tags: ["8-Bit", "Tight Controls", "Nostalgic"],
    description:
      "A love letter to NES-era platformers that plays better than most of the games it's inspired by, bundled with several full campaigns.",
    cover: steamCover(250760),
    backdrop: steamBackdrop(250760),
    stores: {
      steam: { url: steamUrl(250760) },
      gog: { url: gogUrl("shovel_knight_treasure_trove") },
    },
    communityRating: 4.7,
    ratingCount: 19800,
  },
  {
    id: "axiomverge",
    slug: "axiom-verge",
    title: "Axiom Verge",
    year: 2015,
    developer: "Thomas Happ Games",
    publisher: "Thomas Happ Games",
    genres: ["Metroidvania", "Action", "Sci-Fi"],
    tags: ["Retro", "Glitch Aesthetic", "Indie"],
    description:
      "A one-person-made metroidvania soaked in deliberately glitchy sci-fi horror, with a glitch gun that breaks the world on purpose.",
    cover: steamCover(332200),
    backdrop: steamBackdrop(332200),
    stores: {
      steam: { url: steamUrl(332200) },
      gog: { url: gogUrl("axiom_verge") },
    },
    communityRating: 4.3,
    ratingCount: 8900,
  },
  {
    id: "blasphemous",
    slug: "blasphemous",
    title: "Blasphemous",
    year: 2019,
    developer: "The Game Kitchen",
    publisher: "Team17",
    genres: ["Metroidvania", "Action", "Horror"],
    tags: ["Pixel Art", "Religious Horror", "Difficult"],
    description:
      "Grim Catholic-horror pixel art wrapped around a punishing metroidvania. Every boss looks like a Renaissance painting come to life.",
    cover: steamCover(774361),
    backdrop: steamBackdrop(774361),
    stores: {
      steam: { url: steamUrl(774361) },
      gog: { url: gogUrl("blasphemous") },
      epic: { url: epicUrl("blasphemous") },
    },
    communityRating: 4.5,
    ratingCount: 16700,
  },
  {
    id: "saltandsanctuary",
    slug: "salt-and-sanctuary",
    title: "Salt and Sanctuary",
    year: 2016,
    developer: "Ska Studios",
    publisher: "Ska Studios",
    genres: ["Metroidvania", "Souls-like", "Action"],
    tags: ["2D", "Dark Fantasy", "Difficult"],
    description:
      "Dark Souls flattened into 2D and it somehow works perfectly — grim atmosphere, brutal combat, a sprawling interconnected map.",
    cover: steamCover(283640),
    backdrop: steamBackdrop(283640),
    stores: {
      steam: { url: steamUrl(283640) },
      gog: { url: gogUrl("salt_and_sanctuary") },
    },
    communityRating: 4.4,
    ratingCount: 11400,
  },
  {
    id: "guacamelee2",
    slug: "guacamelee-2",
    title: "Guacamelee! 2",
    year: 2018,
    developer: "DrinkBox Studios",
    publisher: "DrinkBox Studios",
    genres: ["Metroidvania", "Platformer", "Comedy"],
    tags: ["Co-op", "Luchador", "Colorful"],
    description:
      "A luchador metroidvania-platformer that never takes itself seriously, with combat and traversal that combine in genuinely clever ways.",
    cover: steamCover(611630),
    backdrop: steamBackdrop(611630),
    stores: { steam: { url: steamUrl(611630) } },
    communityRating: 4.5,
    ratingCount: 6100,
  },
  {
    id: "rainworld",
    slug: "rain-world",
    title: "Rain World",
    year: 2017,
    developer: "Videocult",
    publisher: "Akupara Games",
    genres: ["Metroidvania", "Survival", "Indie"],
    tags: ["Ecosystem Sim", "Difficult", "Atmospheric"],
    description:
      "You're not at the top of the food chain here. A survival-platformer with a living ecosystem that doesn't care if you succeed.",
    cover: steamCover(312520),
    backdrop: steamBackdrop(312520),
    stores: {
      steam: { url: steamUrl(312520) },
      gog: { url: gogUrl("rain_world") },
    },
    communityRating: 4.3,
    ratingCount: 9800,
  },
  {
    id: "persona5royal",
    slug: "persona-5-royal",
    title: "Persona 5 Royal",
    year: 2022,
    developer: "Atlus",
    publisher: "Sega",
    genres: ["RPG", "Turn-Based", "Narrative"],
    tags: ["Anime", "Social Sim", "Story Rich"],
    description:
      "Steal hearts by day, live a double life by night. The definitive version of one of the most stylish JRPGs ever made.",
    cover: steamCover(1687950),
    backdrop: steamBackdrop(1687950),
    stores: { steam: { url: steamUrl(1687950) } },
    communityRating: 4.8,
    ratingCount: 48300,
  },
];

export function getGameBySlug(slug: string) {
  return games.find((g) => g.slug === slug);
}

export function getGameById(id: string) {
  return games.find((g) => g.id === id);
}

export const allGenres = Array.from(new Set(games.flatMap((g) => g.genres))).sort();
