import type { Game } from "./types";

function steamCover(appId: number) {
  return `https://cdn.akamai.steamstatic.com/steam/apps/${appId}/library_600x900.jpg`;
}
function steamBackdrop(appId: number) {
  return `https://cdn.akamai.steamstatic.com/steam/apps/${appId}/library_hero.jpg`;
}
function steamUrl(appId: number) {
  return `https://store.steampowered.com/app/${appId}`;
}
function epicUrl(slug: string) {
  return `https://store.epicgames.com/en-US/p/${slug}`;
}
function gogUrl(slug: string) {
  return `https://www.gog.com/en/game/${slug}`;
}

export const games: Game[] = [
  {
    id: "hl2",
    slug: "half-life-2",
    title: "Half-Life 2",
    year: 2004,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Sci-Fi", "Action"],
    tags: ["Classic", "Story Rich", "Physics"],
    description:
      "Gordon Freeman returns to fight the alien occupation of Earth in a shooter still studied for its pacing, physics puzzles and set-pieces two decades on.",
    cover: steamCover(220),
    backdrop: steamBackdrop(220),
    stores: { steam: { url: steamUrl(220) } },
    communityRating: 4.7,
    ratingCount: 128430,
  },
  {
    id: "portal2",
    slug: "portal-2",
    title: "Portal 2",
    year: 2011,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Puzzle", "Sci-Fi", "Adventure"],
    tags: ["Co-op", "Comedy", "Story Rich"],
    description:
      "A portal gun, a passive-aggressive AI, and some of the best-written puzzle design ever shipped. The co-op campaign is essential.",
    cover: steamCover(620),
    backdrop: steamBackdrop(620),
    stores: { steam: { url: steamUrl(620) } },
    communityRating: 4.9,
    ratingCount: 141220,
  },
  {
    id: "cyberpunk2077",
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    year: 2020,
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Sci-Fi"],
    tags: ["Night City", "First-Person", "Story Rich"],
    description:
      "After a rocky launch, Night City has become one of the densest open worlds around — a cyberpunk crime story with real weight behind its choices.",
    cover: steamCover(1091500),
    backdrop: steamBackdrop(1091500),
    stores: {
      steam: { url: steamUrl(1091500) },
      gog: { url: gogUrl("cyberpunk_2077") },
      epic: { url: epicUrl("cyberpunk-2077-a71bc4") },
    },
    communityRating: 4.4,
    ratingCount: 98220,
  },
  {
    id: "witcher3",
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    year: 2015,
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Fantasy"],
    tags: ["Story Rich", "Monster Hunting", "Classic"],
    description:
      "Geralt's last contract is still the benchmark for open-world RPG writing — every side quest reads like it mattered.",
    cover: steamCover(292030),
    backdrop: steamBackdrop(292030),
    stores: {
      steam: { url: steamUrl(292030) },
      gog: { url: gogUrl("the_witcher_3_wild_hunt") },
      epic: { url: epicUrl("the-witcher-3-wild-hunt") },
    },
    communityRating: 4.9,
    ratingCount: 205110,
  },
  {
    id: "bg3",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genres: ["RPG", "Fantasy", "Strategy"],
    tags: ["Turn-Based", "Co-op", "D&D"],
    description:
      "A turn-based D&D epic with an absurd amount of reactivity — almost anything you try has a hand-built response waiting for it.",
    cover: steamCover(1086940),
    backdrop: steamBackdrop(1086940),
    stores: {
      steam: { url: steamUrl(1086940) },
      gog: { url: gogUrl("baldurs_gate_3") },
    },
    communityRating: 4.9,
    ratingCount: 176500,
  },
  {
    id: "eldenring",
    slug: "elden-ring",
    title: "Elden Ring",
    year: 2022,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Souls-like", "Open World", "Fantasy"],
    tags: ["Difficult", "Atmospheric", "Boss Rush"],
    description:
      "FromSoftware's open world take on the souls formula, co-written with George R. R. Martin's lore — bleak, huge, and unforgiving.",
    cover: steamCover(1245620),
    backdrop: steamBackdrop(1245620),
    stores: { steam: { url: steamUrl(1245620) } },
    communityRating: 4.7,
    ratingCount: 143870,
  },
  {
    id: "hades",
    slug: "hades",
    title: "Hades",
    year: 2020,
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genres: ["Roguelike", "Action", "Indie"],
    tags: ["Greek Mythology", "Story Rich", "Isometric"],
    description:
      "Every failed escape attempt from the Underworld peels back more story. Rare for a roguelike to have this much heart.",
    cover: steamCover(1145360),
    backdrop: steamBackdrop(1145360),
    stores: {
      steam: { url: steamUrl(1145360) },
      gog: { url: gogUrl("hades") },
      epic: { url: epicUrl("hades-c0feb1") },
    },
    communityRating: 4.9,
    ratingCount: 132040,
  },
  {
    id: "stardewvalley",
    slug: "stardew-valley",
    title: "Stardew Valley",
    year: 2016,
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    genres: ["Simulation", "RPG", "Indie"],
    tags: ["Farming", "Cozy", "Multiplayer"],
    description:
      "One developer built a farming sim deep enough to eat entire winters. Still gets free content updates years later.",
    cover: steamCover(413150),
    backdrop: steamBackdrop(413150),
    stores: {
      steam: { url: steamUrl(413150) },
      gog: { url: gogUrl("stardew_valley") },
      epic: { url: epicUrl("stardew-valley") },
    },
    communityRating: 4.8,
    ratingCount: 189330,
  },
  {
    id: "hollowknight",
    slug: "hollow-knight",
    title: "Hollow Knight",
    year: 2017,
    developer: "Team Cherry",
    publisher: "Team Cherry",
    genres: ["Metroidvania", "Indie", "Action"],
    tags: ["Atmospheric", "Difficult", "Hand-Drawn"],
    description:
      "A hand-drawn metroidvania with one of the best-designed maps in the genre and a soundtrack that still lives rent-free.",
    cover: steamCover(367520),
    backdrop: steamBackdrop(367520),
    stores: {
      steam: { url: steamUrl(367520) },
      gog: { url: gogUrl("hollow_knight") },
      epic: { url: epicUrl("hollow-knight") },
    },
    communityRating: 4.8,
    ratingCount: 121980,
  },
  {
    id: "discoelysium",
    slug: "disco-elysium",
    title: "Disco Elysium: The Final Cut",
    year: 2021,
    developer: "ZA/UM",
    publisher: "ZA/UM",
    genres: ["RPG", "Narrative", "Indie"],
    tags: ["Detective", "Dialogue Heavy", "Dark Comedy"],
    description:
      "No combat, all conversation — a detective RPG where your own skills argue with you in your head. Best-in-class writing.",
    cover: steamCover(632470),
    backdrop: steamBackdrop(632470),
    stores: {
      steam: { url: steamUrl(632470) },
      gog: { url: gogUrl("disco_elysium_the_final_cut") },
      epic: { url: epicUrl("disco-elysium-the-final-cut") },
    },
    communityRating: 4.8,
    ratingCount: 60110,
  },
  {
    id: "terraria",
    slug: "terraria",
    title: "Terraria",
    year: 2011,
    developer: "Re-Logic",
    publisher: "Re-Logic",
    genres: ["Sandbox", "Action", "Indie"],
    tags: ["Crafting", "2D", "Multiplayer"],
    description:
      "2D sandbox crafting/adventure that has been quietly getting free major updates for over a decade.",
    cover: steamCover(105600),
    backdrop: steamBackdrop(105600),
    stores: {
      steam: { url: steamUrl(105600) },
      gog: { url: gogUrl("terraria") },
    },
    communityRating: 4.8,
    ratingCount: 175430,
  },
  {
    id: "celeste",
    slug: "celeste",
    title: "Celeste",
    year: 2018,
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    genres: ["Platformer", "Indie"],
    tags: ["Difficult", "Story Rich", "Pixel Art"],
    description:
      "A precision platformer about climbing a mountain and your own anxiety, with some of the tightest movement controls in the genre.",
    cover: steamCover(504230),
    backdrop: steamBackdrop(504230),
    stores: {
      steam: { url: steamUrl(504230) },
      gog: { url: gogUrl("celeste") },
      epic: { url: epicUrl("celeste") },
    },
    communityRating: 4.8,
    ratingCount: 48210,
  },
  {
    id: "deadcells",
    slug: "dead-cells",
    title: "Dead Cells",
    year: 2018,
    developer: "Motion Twin",
    publisher: "Motion Twin",
    genres: ["Roguelike", "Metroidvania", "Action"],
    tags: ["Difficult", "2D", "Fast-Paced"],
    description:
      "A roguevania that controls like a character-action game. Years of free updates have made it one of the deepest builds-based games around.",
    cover: steamCover(588650),
    backdrop: steamBackdrop(588650),
    stores: {
      steam: { url: steamUrl(588650) },
      gog: { url: gogUrl("dead_cells") },
      epic: { url: epicUrl("dead-cells") },
    },
    communityRating: 4.8,
    ratingCount: 71340,
  },
  {
    id: "rdr2",
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    year: 2019,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["Open World", "Action", "Western"],
    tags: ["Story Rich", "Atmospheric", "Realistic"],
    description:
      "An outlaw epic that treats its dying frontier as seriously as its characters — glacial pace, enormous payoff.",
    cover: steamCover(1174180),
    backdrop: steamBackdrop(1174180),
    stores: {
      steam: { url: steamUrl(1174180) },
      epic: { url: epicUrl("red-dead-redemption-2") },
    },
    communityRating: 4.7,
    ratingCount: 156700,
  },
  {
    id: "gtav",
    slug: "grand-theft-auto-v",
    title: "Grand Theft Auto V",
    year: 2013,
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    genres: ["Open World", "Action", "Crime"],
    tags: ["Multiplayer", "Satire", "Classic"],
    description:
      "Three protagonists, one sprawling satire of Southern California, and a GTA Online mode that's outlived every prediction.",
    cover: steamCover(271590),
    backdrop: steamBackdrop(271590),
    stores: {
      steam: { url: steamUrl(271590) },
      epic: { url: epicUrl("grand-theft-auto-v") },
    },
    communityRating: 4.3,
    ratingCount: 198400,
  },
  {
    id: "doometernal",
    slug: "doom-eternal",
    title: "DOOM Eternal",
    year: 2020,
    developer: "id Software",
    publisher: "Bethesda Softworks",
    genres: ["Shooter", "Action"],
    tags: ["Fast-Paced", "Gore", "Metal Soundtrack"],
    description:
      "id Software turns the shooter into a rhythm game of resource management at maximum speed. Exhausting in the best way.",
    cover: steamCover(782330),
    backdrop: steamBackdrop(782330),
    stores: {
      steam: { url: steamUrl(782330) },
      epic: { url: epicUrl("doom-eternal") },
    },
    communityRating: 4.6,
    ratingCount: 65230,
  },
  {
    id: "sekiro",
    slug: "sekiro-shadows-die-twice",
    title: "Sekiro: Shadows Die Twice",
    year: 2019,
    developer: "FromSoftware",
    publisher: "Activision",
    genres: ["Souls-like", "Action", "Fantasy"],
    tags: ["Difficult", "Samurai", "Parry-Focused"],
    description:
      "Posture-breaking swordplay makes this the sharpest combat FromSoftware has ever built, at the cost of any easy mode.",
    cover: steamCover(814380),
    backdrop: steamBackdrop(814380),
    stores: { steam: { url: steamUrl(814380) } },
    communityRating: 4.7,
    ratingCount: 84120,
  },
  {
    id: "darksouls3",
    slug: "dark-souls-3",
    title: "Dark Souls III",
    year: 2016,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Souls-like", "Action", "Fantasy"],
    tags: ["Difficult", "Atmospheric", "Boss Rush"],
    description:
      "The trilogy's send-off, tighter and faster than its predecessors, closing out Lordran's story with some of the series' best bosses.",
    cover: steamCover(374320),
    backdrop: steamBackdrop(374320),
    stores: { steam: { url: steamUrl(374320) } },
    communityRating: 4.7,
    ratingCount: 97650,
  },
  {
    id: "dos2",
    slug: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    year: 2017,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genres: ["RPG", "Strategy", "Fantasy"],
    tags: ["Turn-Based", "Co-op", "Story Rich"],
    description:
      "Larian's warm-up for Baldur's Gate 3 — elemental combos and environmental chaos in a turn-based RPG that rewards creativity.",
    cover: steamCover(435150),
    backdrop: steamBackdrop(435150),
    stores: {
      steam: { url: steamUrl(435150) },
      gog: { url: gogUrl("divinity_original_sin_2") },
      epic: { url: epicUrl("divinity-original-sin-2") },
    },
    communityRating: 4.8,
    ratingCount: 55870,
  },
  {
    id: "slaythespire",
    slug: "slay-the-spire",
    title: "Slay the Spire",
    year: 2019,
    developer: "Mega Crit",
    publisher: "Mega Crit",
    genres: ["Deck-builder", "Roguelike", "Strategy"],
    tags: ["Card Game", "Difficult", "Replayable"],
    description:
      "The game that turned deck-building into a roguelike genre of its own. Endlessly replayable, brutally balanced.",
    cover: steamCover(646570),
    backdrop: steamBackdrop(646570),
    stores: {
      steam: { url: steamUrl(646570) },
      gog: { url: gogUrl("slay_the_spire") },
      epic: { url: epicUrl("slay-the-spire") },
    },
    communityRating: 4.7,
    ratingCount: 61200,
  },
  {
    id: "undertale",
    slug: "undertale",
    title: "Undertale",
    year: 2015,
    developer: "tobyfox",
    publisher: "tobyfox",
    genres: ["RPG", "Indie", "Narrative"],
    tags: ["Story Rich", "Pixel Art", "Comedy"],
    description:
      "A bullet-hell RPG that remembers everything you do and asks whether you needed to fight at all. Still catches people off guard.",
    cover: steamCover(391540),
    backdrop: steamBackdrop(391540),
    stores: {
      steam: { url: steamUrl(391540) },
      gog: { url: gogUrl("undertale") },
    },
    communityRating: 4.8,
    ratingCount: 88450,
  },
  {
    id: "oriwotw",
    slug: "ori-and-the-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    year: 2020,
    developer: "Moon Studios",
    publisher: "Xbox Game Studios",
    genres: ["Metroidvania", "Platformer", "Adventure"],
    tags: ["Beautiful", "Atmospheric", "Story Rich"],
    description:
      "Some of the most gorgeous hand-painted backdrops in the genre, wrapped around movement that feels incredible by the final act.",
    cover: steamCover(1057090),
    backdrop: steamBackdrop(1057090),
    stores: {
      steam: { url: steamUrl(1057090) },
      epic: { url: epicUrl("ori-and-the-will-of-the-wisps") },
    },
    communityRating: 4.8,
    ratingCount: 26340,
  },
  {
    id: "ittakestwo",
    slug: "it-takes-two",
    title: "It Takes Two",
    year: 2021,
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    genres: ["Platformer", "Adventure", "Co-op"],
    tags: ["Co-op Only", "Inventive", "Story Rich"],
    description:
      "A two-player-only adventure that reinvents its core mechanics almost every chapter. Rare to see this much ambition in co-op design.",
    cover: steamCover(1426210),
    backdrop: steamBackdrop(1426210),
    stores: {
      steam: { url: steamUrl(1426210) },
      epic: { url: epicUrl("it-takes-two") },
    },
    communityRating: 4.8,
    ratingCount: 42110,
  },
  {
    id: "balatro",
    slug: "balatro",
    title: "Balatro",
    year: 2024,
    developer: "LocalThunk",
    publisher: "Playstack",
    genres: ["Deck-builder", "Roguelike", "Card Game"],
    tags: ["Poker", "Addictive", "Indie"],
    description:
      "Poker-hand scoring turned into a roguelike deck-builder that eats entire evenings without you noticing. Deceptively deep.",
    cover: steamCover(2379780),
    backdrop: steamBackdrop(2379780),
    stores: {
      steam: { url: steamUrl(2379780) },
      gog: { url: gogUrl("balatro") },
      epic: { url: epicUrl("balatro") },
    },
    communityRating: 4.8,
    ratingCount: 39870,
  },
  {
    id: "vampiresurvivors",
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    year: 2022,
    developer: "poncle",
    publisher: "poncle",
    genres: ["Roguelike", "Action", "Indie"],
    tags: ["Bullet Heaven", "Pixel Art", "Cheap"],
    description:
      "The game that named an entire new genre. Absurdly cheap, absurdly replayable auto-battling chaos.",
    cover: steamCover(1794680),
    backdrop: steamBackdrop(1794680),
    stores: {
      steam: { url: steamUrl(1794680) },
      gog: { url: gogUrl("vampire_survivors") },
      epic: { url: epicUrl("vampire-survivors") },
    },
    communityRating: 4.7,
    ratingCount: 40120,
  },
  {
    id: "outerwilds",
    slug: "outer-wilds",
    title: "Outer Wilds",
    year: 2019,
    developer: "Mobius Digital",
    publisher: "Annapurna Interactive",
    genres: ["Adventure", "Puzzle", "Sci-Fi"],
    tags: ["Mystery", "Exploration", "Time Loop"],
    description:
      "A 22-minute time loop and a solar system full of secrets. Knowledge is the only upgrade, which makes every discovery permanent.",
    cover: steamCover(753640),
    backdrop: steamBackdrop(753640),
    stores: {
      steam: { url: steamUrl(753640) },
      epic: { url: epicUrl("outer-wilds") },
    },
    communityRating: 4.9,
    ratingCount: 33980,
  },
  {
    id: "cultofthelamb",
    slug: "cult-of-the-lamb",
    title: "Cult of the Lamb",
    year: 2022,
    developer: "Massive Monster",
    publisher: "Devolver Digital",
    genres: ["Roguelike", "Simulation", "Indie"],
    tags: ["Cute", "Dark Comedy", "Base Building"],
    description:
      "Run a cult by day, roguelike your way through corrupted lands by night. Devolver's chaotic sense of humor all over it.",
    cover: steamCover(1313140),
    backdrop: steamBackdrop(1313140),
    stores: {
      steam: { url: steamUrl(1313140) },
      gog: { url: gogUrl("cult_of_the_lamb") },
      epic: { url: epicUrl("cult-of-the-lamb") },
    },
    communityRating: 4.5,
    ratingCount: 28770,
  },
  {
    id: "control",
    slug: "control",
    title: "Control",
    year: 2019,
    developer: "Remedy Entertainment",
    publisher: "505 Games",
    genres: ["Action", "Sci-Fi", "Adventure"],
    tags: ["Atmospheric", "Telekinesis", "Story Rich"],
    description:
      "Remedy's brutalist bureaucratic horror, with telekinetic combat that turns entire offices into ammunition.",
    cover: steamCover(870780),
    backdrop: steamBackdrop(870780),
    stores: {
      steam: { url: steamUrl(870780) },
      epic: { url: epicUrl("control") },
    },
    communityRating: 4.5,
    ratingCount: 31200,
  },
  {
    id: "portal",
    slug: "portal",
    title: "Portal",
    year: 2007,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Puzzle", "Sci-Fi", "Adventure"],
    tags: ["Classic", "Short", "Comedy"],
    description:
      "The one that started it all — a four-hour puzzle box that rewired how people think about first-person game design.",
    cover: steamCover(400),
    backdrop: steamBackdrop(400),
    stores: { steam: { url: steamUrl(400) } },
    communityRating: 4.9,
    ratingCount: 98650,
  },
  {
    id: "tf2",
    slug: "team-fortress-2",
    title: "Team Fortress 2",
    year: 2007,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Action"],
    tags: ["Free to Play", "Class-Based", "Multiplayer"],
    description:
      "Nine overdesigned classes, near-perfect map design, and a hat economy that somehow still runs. Still one of the best shooters made.",
    cover: steamCover(440),
    backdrop: steamBackdrop(440),
    stores: { steam: { url: steamUrl(440) } },
    communityRating: 4.6,
    ratingCount: 87340,
  },
  {
    id: "cs2",
    slug: "counter-strike-2",
    title: "Counter-Strike 2",
    year: 2023,
    developer: "Valve",
    publisher: "Valve",
    genres: ["Shooter", "Action", "Esports"],
    tags: ["Free to Play", "Competitive", "Tactical"],
    description:
      "The reigning tactical shooter, rebuilt on Source 2. Still the benchmark for gunplay precision two decades into the franchise.",
    cover: steamCover(730),
    backdrop: steamBackdrop(730),
    stores: { steam: { url: steamUrl(730) } },
    communityRating: 4.3,
    ratingCount: 154200,
  },
  {
    id: "rocketleague",
    slug: "rocket-league",
    title: "Rocket League",
    year: 2015,
    developer: "Psyonix",
    publisher: "Psyonix",
    genres: ["Sports", "Action", "Multiplayer"],
    tags: ["Free to Play", "Competitive", "Cars"],
    description:
      "Soccer, but with rocket-powered cars. Simple pitch, absurdly deep skill ceiling once you learn to fly.",
    cover: steamCover(252950),
    backdrop: steamBackdrop(252950),
    stores: {
      steam: { url: steamUrl(252950) },
      epic: { url: epicUrl("rocket-league") },
    },
    communityRating: 4.5,
    ratingCount: 112400,
  },
  {
    id: "amongus",
    slug: "among-us",
    title: "Among Us",
    year: 2018,
    developer: "InnerSloth",
    publisher: "InnerSloth",
    genres: ["Social Deduction", "Multiplayer", "Indie"],
    tags: ["Party Game", "Cross-Platform", "Cheap"],
    description:
      "A lobby of nine crewmates and a saboteur or two. The 2020 sleeper hit that made everyone suspicious of their friends.",
    cover: steamCover(945360),
    backdrop: steamBackdrop(945360),
    stores: {
      steam: { url: steamUrl(945360) },
      gog: { url: gogUrl("among_us") },
      epic: { url: epicUrl("among-us") },
    },
    communityRating: 4.2,
    ratingCount: 76300,
  },
  {
    id: "cuphead",
    slug: "cuphead",
    title: "Cuphead",
    year: 2017,
    developer: "StudioMDHR",
    publisher: "StudioMDHR",
    genres: ["Platformer", "Action", "Indie"],
    tags: ["Difficult", "Hand-Drawn", "Boss Rush"],
    description:
      "Hand-inked 1930s cartoon aesthetics wrapped around a run-and-gun that shows zero mercy. The art alone took years.",
    cover: steamCover(268910),
    backdrop: steamBackdrop(268910),
    stores: {
      steam: { url: steamUrl(268910) },
      gog: { url: gogUrl("cuphead") },
      epic: { url: epicUrl("cuphead") },
    },
    communityRating: 4.7,
    ratingCount: 68900,
  },
  {
    id: "firewatch",
    slug: "firewatch",
    title: "Firewatch",
    year: 2016,
    developer: "Campo Santo",
    publisher: "Panic",
    genres: ["Narrative", "Adventure", "Indie"],
    tags: ["Story Rich", "First-Person", "Atmospheric"],
    description:
      "Two people talk on a radio in a Wyoming forest and it somehow becomes one of the best-written games of the decade.",
    cover: steamCover(383870),
    backdrop: steamBackdrop(383870),
    stores: {
      steam: { url: steamUrl(383870) },
      gog: { url: gogUrl("firewatch") },
      epic: { url: epicUrl("firewatch") },
    },
    communityRating: 4.4,
    ratingCount: 41200,
  },
  {
    id: "hyperlightdrifter",
    slug: "hyper-light-drifter",
    title: "Hyper Light Drifter",
    year: 2016,
    developer: "Heart Machine",
    publisher: "Heart Machine",
    genres: ["Action", "Adventure", "Indie"],
    tags: ["Pixel Art", "Atmospheric", "Difficult"],
    description:
      "A wordless, dying world told entirely through pixel art and a combat system with real weight behind every swing.",
    cover: steamCover(257850),
    backdrop: steamBackdrop(257850),
    stores: {
      steam: { url: steamUrl(257850) },
      gog: { url: gogUrl("hyper_light_drifter") },
      epic: { url: epicUrl("hyper-light-drifter") },
    },
    communityRating: 4.5,
    ratingCount: 29800,
  },
  {
    id: "katanazero",
    slug: "katana-zero",
    title: "Katana ZERO",
    year: 2019,
    developer: "Askiisoft",
    publisher: "Devolver Digital",
    genres: ["Platformer", "Action", "Indie"],
    tags: ["Neo-Noir", "One-Hit Kill", "Story Rich"],
    description:
      "One-hit-kill action with a rewind mechanic and a neo-noir story that keeps getting stranger. Over too soon in the best way.",
    cover: steamCover(460950),
    backdrop: steamBackdrop(460950),
    stores: {
      steam: { url: steamUrl(460950) },
      gog: { url: gogUrl("katana_zero") },
      epic: { url: epicUrl("katana-zero") },
    },
    communityRating: 4.7,
    ratingCount: 33500,
  },
  {
    id: "inscryption",
    slug: "inscryption",
    title: "Inscryption",
    year: 2021,
    developer: "Daniel Mullins Games",
    publisher: "Devolver Digital",
    genres: ["Deck-builder", "Horror", "Puzzle"],
    tags: ["Card Game", "Story Rich", "Meta"],
    description:
      "A card-battling roguelike that keeps breaking its own frame. Say as little about it going in as possible.",
    cover: steamCover(1092790),
    backdrop: steamBackdrop(1092790),
    stores: {
      steam: { url: steamUrl(1092790) },
      gog: { url: gogUrl("inscryption") },
      epic: { url: epicUrl("inscryption") },
    },
    communityRating: 4.8,
    ratingCount: 37600,
  },
  {
    id: "inside",
    slug: "inside",
    title: "Inside",
    year: 2016,
    developer: "Playdead",
    publisher: "Playdead",
    genres: ["Puzzle", "Platformer", "Horror"],
    tags: ["Atmospheric", "Story Rich", "Short"],
    description:
      "A silent, unsettling puzzle-platformer from the Limbo team, with an ending people are still arguing about.",
    cover: steamCover(304430),
    backdrop: steamBackdrop(304430),
    stores: {
      steam: { url: steamUrl(304430) },
      gog: { url: gogUrl("inside") },
      epic: { url: epicUrl("inside") },
    },
    communityRating: 4.7,
    ratingCount: 44100,
  },
  {
    id: "limbo",
    slug: "limbo",
    title: "Limbo",
    year: 2011,
    developer: "Playdead",
    publisher: "Playdead",
    genres: ["Puzzle", "Platformer", "Horror"],
    tags: ["Atmospheric", "Black and White", "Short"],
    description:
      "The monochrome puzzle-platformer that proved indie games could be genuinely unsettling. Still holds up.",
    cover: steamCover(48000),
    backdrop: steamBackdrop(48000),
    stores: {
      steam: { url: steamUrl(48000) },
      gog: { url: gogUrl("limbo") },
      epic: { url: epicUrl("limbo") },
    },
    communityRating: 4.6,
    ratingCount: 52300,
  },
  {
    id: "stanleyparable",
    slug: "the-stanley-parable-ultra-deluxe",
    title: "The Stanley Parable: Ultra Deluxe",
    year: 2022,
    developer: "Crows Crows Crows",
    publisher: "Crows Crows Crows",
    genres: ["Narrative", "Puzzle", "Comedy"],
    tags: ["Meta", "First-Person", "Satire"],
    description:
      "A choice-driven walking sim that spends its entire runtime mocking the idea of choice-driven walking sims. Extremely funny.",
    cover: steamCover(1703340),
    backdrop: steamBackdrop(1703340),
    stores: {
      steam: { url: steamUrl(1703340) },
      gog: { url: gogUrl("the_stanley_parable_ultra_deluxe") },
      epic: { url: epicUrl("the-stanley-parable-ultra-deluxe") },
    },
    communityRating: 4.6,
    ratingCount: 22100,
  },
  {
    id: "superliminal",
    slug: "superliminal",
    title: "Superliminal",
    year: 2019,
    developer: "Pillow Castle",
    publisher: "Pillow Castle",
    genres: ["Puzzle", "First-Person", "Indie"],
    tags: ["Perspective", "Short", "Trippy"],
    description:
      "A first-person puzzle game about forced perspective that keeps finding new ways to break your brain in a good way.",
    cover: steamCover(1049410),
    backdrop: steamBackdrop(1049410),
    stores: {
      steam: { url: steamUrl(1049410) },
      gog: { url: gogUrl("superliminal") },
      epic: { url: epicUrl("superliminal") },
    },
    communityRating: 4.4,
    ratingCount: 18700,
  },
  {
    id: "tunic",
    slug: "tunic",
    title: "Tunic",
    year: 2022,
    developer: "Isometricorp Games",
    publisher: "Finji",
    genres: ["Action", "Adventure", "Metroidvania"],
    tags: ["Zelda-Like", "Puzzle", "Instruction Manual"],
    description:
      "A tiny fox in a Zelda-like world, with an in-game instruction manual that turns into the real puzzle. Deeply clever.",
    cover: steamCover(553420),
    backdrop: steamBackdrop(553420),
    stores: {
      steam: { url: steamUrl(553420) },
      gog: { url: gogUrl("tunic") },
      epic: { url: epicUrl("tunic") },
    },
    communityRating: 4.6,
    ratingCount: 19400,
  },
  {
    id: "loophero",
    slug: "loop-hero",
    title: "Loop Hero",
    year: 2021,
    developer: "Four Quarters",
    publisher: "Devolver Digital",
    genres: ["Roguelike", "Strategy", "Indie"],
    tags: ["Deck-builder", "Pixel Art", "Automation"],
    description:
      "You place the tiles that build the world your hero walks in an endless loop. One of the most original roguelikes in years.",
    cover: steamCover(1282730),
    backdrop: steamBackdrop(1282730),
    stores: {
      steam: { url: steamUrl(1282730) },
      gog: { url: gogUrl("loop_hero") },
      epic: { url: epicUrl("loop-hero") },
    },
    communityRating: 4.5,
    ratingCount: 16200,
  },
  {
    id: "subnautica",
    slug: "subnautica",
    title: "Subnautica",
    year: 2018,
    developer: "Unknown Worlds Entertainment",
    publisher: "Unknown Worlds Entertainment",
    genres: ["Survival", "Adventure", "Open World"],
    tags: ["Underwater", "Crafting", "Atmospheric"],
    description:
      "An ocean survival game that turns thalassophobia into a core mechanic. Beautiful right up until something huge swims past.",
    cover: steamCover(264710),
    backdrop: steamBackdrop(264710),
    stores: {
      steam: { url: steamUrl(264710) },
      epic: { url: epicUrl("subnautica") },
    },
    communityRating: 4.7,
    ratingCount: 84600,
  },
  {
    id: "untitledgoosegame",
    slug: "untitled-goose-game",
    title: "Untitled Goose Game",
    year: 2019,
    developer: "House House",
    publisher: "Panic",
    genres: ["Puzzle", "Comedy", "Indie"],
    tags: ["Short", "Physics", "Silly"],
    description:
      "You are a horrible goose terrorizing an English village. A whole cultural moment for one very good comedic premise.",
    cover: steamCover(1046030),
    backdrop: steamBackdrop(1046030),
    stores: {
      steam: { url: steamUrl(1046030) },
      epic: { url: epicUrl("untitled-goose-game") },
    },
    communityRating: 4.3,
    ratingCount: 20900,
  },
  {
    id: "edithfinch",
    slug: "what-remains-of-edith-finch",
    title: "What Remains of Edith Finch",
    year: 2017,
    developer: "Giant Sparrow",
    publisher: "Annapurna Interactive",
    genres: ["Narrative", "Adventure", "Indie"],
    tags: ["Story Rich", "Short", "Emotional"],
    description:
      "A house full of dead relatives, each with a wildly different vignette telling their story. One of the best cases for games as fiction.",
    cover: steamCover(501300),
    backdrop: steamBackdrop(501300),
    stores: {
      steam: { url: steamUrl(501300) },
      epic: { url: epicUrl("what-remains-of-edith-finch") },
    },
    communityRating: 4.6,
    ratingCount: 27300,
  },
  {
    id: "riskofrain2",
    slug: "risk-of-rain-2",
    title: "Risk of Rain 2",
    year: 2020,
    developer: "Hopoo Games",
    publisher: "Gearbox Publishing",
    genres: ["Roguelike", "Shooter", "Action"],
    tags: ["Co-op", "3D", "Replayable"],
    description:
      "The 2D cult classic rebuilt in 3D without losing what made it work — stack absurd items until you become a walking apocalypse.",
    cover: steamCover(632360),
    backdrop: steamBackdrop(632360),
    stores: {
      steam: { url: steamUrl(632360) },
      epic: { url: epicUrl("risk-of-rain-2") },
    },
    communityRating: 4.6,
    ratingCount: 45700,
  },
];

export function getGameBySlug(slug: string) {
  return games.find((g) => g.slug === slug);
}

export function getGameById(id: string) {
  return games.find((g) => g.id === id);
}

export const allGenres = Array.from(new Set(games.flatMap((g) => g.genres))).sort();
